// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: douyin.proto

// Protobuf Java Version: 3.25.1
package cn.yscme.scrolling.auto.douyin;

public interface CommonOrBuilder extends
        // @@protoc_insertion_point(interface_extends:cn.yscme.scrolling.auto.douyin.Common)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string method = 1;</code>
     *
     * @return The method.
     */
    java.lang.String getMethod();

    /**
     * <code>string method = 1;</code>
     *
     * @return The bytes for method.
     */
    com.google.protobuf.ByteString
    getMethodBytes();

    /**
     * <code>uint64 msgId = 2;</code>
     *
     * @return The msgId.
     */
    long getMsgId();

    /**
     * <code>uint64 roomId = 3;</code>
     *
     * @return The roomId.
     */
    long getRoomId();

    /**
     * <code>uint64 createTime = 4;</code>
     *
     * @return The createTime.
     */
    long getCreateTime();

    /**
     * <code>uint32 monitor = 5;</code>
     *
     * @return The monitor.
     */
    int getMonitor();

    /**
     * <code>bool isShowMsg = 6;</code>
     *
     * @return The isShowMsg.
     */
    boolean getIsShowMsg();

    /**
     * <code>string describe = 7;</code>
     *
     * @return The describe.
     */
    java.lang.String getDescribe();

    /**
     * <code>string describe = 7;</code>
     *
     * @return The bytes for describe.
     */
    com.google.protobuf.ByteString
    getDescribeBytes();

    /**
     * <pre>
     *  DisplayText displayText = 8;
     * </pre>
     *
     * <code>uint64 foldType = 9;</code>
     *
     * @return The foldType.
     */
    long getFoldType();

    /**
     * <code>uint64 anchorFoldType = 10;</code>
     *
     * @return The anchorFoldType.
     */
    long getAnchorFoldType();

    /**
     * <code>uint64 priorityScore = 11;</code>
     *
     * @return The priorityScore.
     */
    long getPriorityScore();

    /**
     * <code>string logId = 12;</code>
     *
     * @return The logId.
     */
    java.lang.String getLogId();

    /**
     * <code>string logId = 12;</code>
     *
     * @return The bytes for logId.
     */
    com.google.protobuf.ByteString
    getLogIdBytes();

    /**
     * <code>string msgProcessFilterK = 13;</code>
     *
     * @return The msgProcessFilterK.
     */
    java.lang.String getMsgProcessFilterK();

    /**
     * <code>string msgProcessFilterK = 13;</code>
     *
     * @return The bytes for msgProcessFilterK.
     */
    com.google.protobuf.ByteString
    getMsgProcessFilterKBytes();

    /**
     * <code>string msgProcessFilterV = 14;</code>
     *
     * @return The msgProcessFilterV.
     */
    java.lang.String getMsgProcessFilterV();

    /**
     * <code>string msgProcessFilterV = 14;</code>
     *
     * @return The bytes for msgProcessFilterV.
     */
    com.google.protobuf.ByteString
    getMsgProcessFilterVBytes();

    /**
     * <code>.cn.yscme.scrolling.auto.douyin.User user = 15;</code>
     *
     * @return Whether the user field is set.
     */
    boolean hasUser();

    /**
     * <code>.cn.yscme.scrolling.auto.douyin.User user = 15;</code>
     *
     * @return The user.
     */
    cn.yscme.scrolling.auto.douyin.User getUser();

    /**
     * <code>.cn.yscme.scrolling.auto.douyin.User user = 15;</code>
     */
    cn.yscme.scrolling.auto.douyin.UserOrBuilder getUserOrBuilder();

    /**
     * <pre>
     *  Room room = 16;
     * </pre>
     *
     * <code>uint64 anchorFoldTypeV2 = 17;</code>
     *
     * @return The anchorFoldTypeV2.
     */
    long getAnchorFoldTypeV2();

    /**
     * <code>uint64 processAtSeiTimeMs = 18;</code>
     *
     * @return The processAtSeiTimeMs.
     */
    long getProcessAtSeiTimeMs();

    /**
     * <code>uint64 randomDispatchMs = 19;</code>
     *
     * @return The randomDispatchMs.
     */
    long getRandomDispatchMs();

    /**
     * <code>bool isDispatch = 20;</code>
     *
     * @return The isDispatch.
     */
    boolean getIsDispatch();

    /**
     * <code>uint64 channelId = 21;</code>
     *
     * @return The channelId.
     */
    long getChannelId();

    /**
     * <code>uint64 diffSei2absSecond = 22;</code>
     *
     * @return The diffSei2absSecond.
     */
    long getDiffSei2AbsSecond();

    /**
     * <code>uint64 anchorFoldDuration = 23;</code>
     *
     * @return The anchorFoldDuration.
     */
    long getAnchorFoldDuration();
}
