// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: douyin.proto

// Protobuf Java Version: 3.25.1
package cn.yscme.scrolling.auto.douyin;

public interface ControlMessageOrBuilder extends
        // @@protoc_insertion_point(interface_extends:cn.yscme.scrolling.auto.douyin.ControlMessage)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.cn.yscme.scrolling.auto.douyin.Common common = 1;</code>
     *
     * @return Whether the common field is set.
     */
    boolean hasCommon();

    /**
     * <code>.cn.yscme.scrolling.auto.douyin.Common common = 1;</code>
     *
     * @return The common.
     */
    cn.yscme.scrolling.auto.douyin.Common getCommon();

    /**
     * <code>.cn.yscme.scrolling.auto.douyin.Common common = 1;</code>
     */
    cn.yscme.scrolling.auto.douyin.CommonOrBuilder getCommonOrBuilder();

    /**
     * <code>int32 status = 2;</code>
     *
     * @return The status.
     */
    int getStatus();
}
