// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: douyin.proto

// Protobuf Java Version: 3.25.1
package cn.yscme.scrolling.auto.douyin;

/**
 * Protobuf type {@code cn.yscme.scrolling.auto.douyin.LiveShoppingMessage}
 */
public final class LiveShoppingMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:cn.yscme.scrolling.auto.douyin.LiveShoppingMessage)
    LiveShoppingMessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use LiveShoppingMessage.newBuilder() to construct.
  private LiveShoppingMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private LiveShoppingMessage() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new LiveShoppingMessage();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return cn.yscme.scrolling.auto.douyin.Douyin.internal_static_cn_yscme_scrolling_auto_douyin_LiveShoppingMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return cn.yscme.scrolling.auto.douyin.Douyin.internal_static_cn_yscme_scrolling_auto_douyin_LiveShoppingMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            cn.yscme.scrolling.auto.douyin.LiveShoppingMessage.class, cn.yscme.scrolling.auto.douyin.LiveShoppingMessage.Builder.class);
  }

  private int bitField0_;
  public static final int COMMON_FIELD_NUMBER = 1;
  private cn.yscme.scrolling.auto.douyin.Common common_;
  /**
   * <code>.cn.yscme.scrolling.auto.douyin.Common common = 1;</code>
   * @return Whether the common field is set.
   */
  @java.lang.Override
  public boolean hasCommon() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.cn.yscme.scrolling.auto.douyin.Common common = 1;</code>
   * @return The common.
   */
  @java.lang.Override
  public cn.yscme.scrolling.auto.douyin.Common getCommon() {
    return common_ == null ? cn.yscme.scrolling.auto.douyin.Common.getDefaultInstance() : common_;
  }
  /**
   * <code>.cn.yscme.scrolling.auto.douyin.Common common = 1;</code>
   */
  @java.lang.Override
  public cn.yscme.scrolling.auto.douyin.CommonOrBuilder getCommonOrBuilder() {
    return common_ == null ? cn.yscme.scrolling.auto.douyin.Common.getDefaultInstance() : common_;
  }

  public static final int MSGTYPE_FIELD_NUMBER = 2;
  private int msgType_ = 0;
  /**
   * <code>int32 msgType = 2;</code>
   * @return The msgType.
   */
  @java.lang.Override
  public int getMsgType() {
    return msgType_;
  }

  public static final int PROMOTIONID_FIELD_NUMBER = 4;
  private long promotionId_ = 0L;
  /**
   * <code>int64 promotionId = 4;</code>
   * @return The promotionId.
   */
  @java.lang.Override
  public long getPromotionId() {
    return promotionId_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getCommon());
    }
    if (msgType_ != 0) {
      output.writeInt32(2, msgType_);
    }
    if (promotionId_ != 0L) {
      output.writeInt64(4, promotionId_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getCommon());
    }
    if (msgType_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, msgType_);
    }
    if (promotionId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, promotionId_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof cn.yscme.scrolling.auto.douyin.LiveShoppingMessage)) {
      return super.equals(obj);
    }
    cn.yscme.scrolling.auto.douyin.LiveShoppingMessage other = (cn.yscme.scrolling.auto.douyin.LiveShoppingMessage) obj;

    if (hasCommon() != other.hasCommon()) return false;
    if (hasCommon()) {
      if (!getCommon()
          .equals(other.getCommon())) return false;
    }
    if (getMsgType()
        != other.getMsgType()) return false;
    if (getPromotionId()
        != other.getPromotionId()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasCommon()) {
      hash = (37 * hash) + COMMON_FIELD_NUMBER;
      hash = (53 * hash) + getCommon().hashCode();
    }
    hash = (37 * hash) + MSGTYPE_FIELD_NUMBER;
    hash = (53 * hash) + getMsgType();
    hash = (37 * hash) + PROMOTIONID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getPromotionId());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static cn.yscme.scrolling.auto.douyin.LiveShoppingMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cn.yscme.scrolling.auto.douyin.LiveShoppingMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cn.yscme.scrolling.auto.douyin.LiveShoppingMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cn.yscme.scrolling.auto.douyin.LiveShoppingMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cn.yscme.scrolling.auto.douyin.LiveShoppingMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cn.yscme.scrolling.auto.douyin.LiveShoppingMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cn.yscme.scrolling.auto.douyin.LiveShoppingMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static cn.yscme.scrolling.auto.douyin.LiveShoppingMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static cn.yscme.scrolling.auto.douyin.LiveShoppingMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static cn.yscme.scrolling.auto.douyin.LiveShoppingMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static cn.yscme.scrolling.auto.douyin.LiveShoppingMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static cn.yscme.scrolling.auto.douyin.LiveShoppingMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(cn.yscme.scrolling.auto.douyin.LiveShoppingMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code cn.yscme.scrolling.auto.douyin.LiveShoppingMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:cn.yscme.scrolling.auto.douyin.LiveShoppingMessage)
      cn.yscme.scrolling.auto.douyin.LiveShoppingMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.yscme.scrolling.auto.douyin.Douyin.internal_static_cn_yscme_scrolling_auto_douyin_LiveShoppingMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.yscme.scrolling.auto.douyin.Douyin.internal_static_cn_yscme_scrolling_auto_douyin_LiveShoppingMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.yscme.scrolling.auto.douyin.LiveShoppingMessage.class, cn.yscme.scrolling.auto.douyin.LiveShoppingMessage.Builder.class);
    }

    // Construct using cn.yscme.scrolling.auto.douyin.LiveShoppingMessage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getCommonFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      common_ = null;
      if (commonBuilder_ != null) {
        commonBuilder_.dispose();
        commonBuilder_ = null;
      }
      msgType_ = 0;
      promotionId_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return cn.yscme.scrolling.auto.douyin.Douyin.internal_static_cn_yscme_scrolling_auto_douyin_LiveShoppingMessage_descriptor;
    }

    @java.lang.Override
    public cn.yscme.scrolling.auto.douyin.LiveShoppingMessage getDefaultInstanceForType() {
      return cn.yscme.scrolling.auto.douyin.LiveShoppingMessage.getDefaultInstance();
    }

    @java.lang.Override
    public cn.yscme.scrolling.auto.douyin.LiveShoppingMessage build() {
      cn.yscme.scrolling.auto.douyin.LiveShoppingMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public cn.yscme.scrolling.auto.douyin.LiveShoppingMessage buildPartial() {
      cn.yscme.scrolling.auto.douyin.LiveShoppingMessage result = new cn.yscme.scrolling.auto.douyin.LiveShoppingMessage(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(cn.yscme.scrolling.auto.douyin.LiveShoppingMessage result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.common_ = commonBuilder_ == null
            ? common_
            : commonBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.msgType_ = msgType_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.promotionId_ = promotionId_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof cn.yscme.scrolling.auto.douyin.LiveShoppingMessage) {
        return mergeFrom((cn.yscme.scrolling.auto.douyin.LiveShoppingMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(cn.yscme.scrolling.auto.douyin.LiveShoppingMessage other) {
      if (other == cn.yscme.scrolling.auto.douyin.LiveShoppingMessage.getDefaultInstance()) return this;
      if (other.hasCommon()) {
        mergeCommon(other.getCommon());
      }
      if (other.getMsgType() != 0) {
        setMsgType(other.getMsgType());
      }
      if (other.getPromotionId() != 0L) {
        setPromotionId(other.getPromotionId());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getCommonFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              msgType_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 32: {
              promotionId_ = input.readInt64();
              bitField0_ |= 0x00000004;
              break;
            } // case 32
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private cn.yscme.scrolling.auto.douyin.Common common_;
    private com.google.protobuf.SingleFieldBuilderV3<
        cn.yscme.scrolling.auto.douyin.Common, cn.yscme.scrolling.auto.douyin.Common.Builder, cn.yscme.scrolling.auto.douyin.CommonOrBuilder> commonBuilder_;
    /**
     * <code>.cn.yscme.scrolling.auto.douyin.Common common = 1;</code>
     * @return Whether the common field is set.
     */
    public boolean hasCommon() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.cn.yscme.scrolling.auto.douyin.Common common = 1;</code>
     * @return The common.
     */
    public cn.yscme.scrolling.auto.douyin.Common getCommon() {
      if (commonBuilder_ == null) {
        return common_ == null ? cn.yscme.scrolling.auto.douyin.Common.getDefaultInstance() : common_;
      } else {
        return commonBuilder_.getMessage();
      }
    }
    /**
     * <code>.cn.yscme.scrolling.auto.douyin.Common common = 1;</code>
     */
    public Builder setCommon(cn.yscme.scrolling.auto.douyin.Common value) {
      if (commonBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        common_ = value;
      } else {
        commonBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.cn.yscme.scrolling.auto.douyin.Common common = 1;</code>
     */
    public Builder setCommon(
        cn.yscme.scrolling.auto.douyin.Common.Builder builderForValue) {
      if (commonBuilder_ == null) {
        common_ = builderForValue.build();
      } else {
        commonBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.cn.yscme.scrolling.auto.douyin.Common common = 1;</code>
     */
    public Builder mergeCommon(cn.yscme.scrolling.auto.douyin.Common value) {
      if (commonBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          common_ != null &&
          common_ != cn.yscme.scrolling.auto.douyin.Common.getDefaultInstance()) {
          getCommonBuilder().mergeFrom(value);
        } else {
          common_ = value;
        }
      } else {
        commonBuilder_.mergeFrom(value);
      }
      if (common_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.cn.yscme.scrolling.auto.douyin.Common common = 1;</code>
     */
    public Builder clearCommon() {
      bitField0_ = (bitField0_ & ~0x00000001);
      common_ = null;
      if (commonBuilder_ != null) {
        commonBuilder_.dispose();
        commonBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.cn.yscme.scrolling.auto.douyin.Common common = 1;</code>
     */
    public cn.yscme.scrolling.auto.douyin.Common.Builder getCommonBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getCommonFieldBuilder().getBuilder();
    }
    /**
     * <code>.cn.yscme.scrolling.auto.douyin.Common common = 1;</code>
     */
    public cn.yscme.scrolling.auto.douyin.CommonOrBuilder getCommonOrBuilder() {
      if (commonBuilder_ != null) {
        return commonBuilder_.getMessageOrBuilder();
      } else {
        return common_ == null ?
            cn.yscme.scrolling.auto.douyin.Common.getDefaultInstance() : common_;
      }
    }
    /**
     * <code>.cn.yscme.scrolling.auto.douyin.Common common = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        cn.yscme.scrolling.auto.douyin.Common, cn.yscme.scrolling.auto.douyin.Common.Builder, cn.yscme.scrolling.auto.douyin.CommonOrBuilder> 
        getCommonFieldBuilder() {
      if (commonBuilder_ == null) {
        commonBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            cn.yscme.scrolling.auto.douyin.Common, cn.yscme.scrolling.auto.douyin.Common.Builder, cn.yscme.scrolling.auto.douyin.CommonOrBuilder>(
                getCommon(),
                getParentForChildren(),
                isClean());
        common_ = null;
      }
      return commonBuilder_;
    }

    private int msgType_ ;
    /**
     * <code>int32 msgType = 2;</code>
     * @return The msgType.
     */
    @java.lang.Override
    public int getMsgType() {
      return msgType_;
    }
    /**
     * <code>int32 msgType = 2;</code>
     * @param value The msgType to set.
     * @return This builder for chaining.
     */
    public Builder setMsgType(int value) {

      msgType_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int32 msgType = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearMsgType() {
      bitField0_ = (bitField0_ & ~0x00000002);
      msgType_ = 0;
      onChanged();
      return this;
    }

    private long promotionId_ ;
    /**
     * <code>int64 promotionId = 4;</code>
     * @return The promotionId.
     */
    @java.lang.Override
    public long getPromotionId() {
      return promotionId_;
    }
    /**
     * <code>int64 promotionId = 4;</code>
     * @param value The promotionId to set.
     * @return This builder for chaining.
     */
    public Builder setPromotionId(long value) {

      promotionId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int64 promotionId = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearPromotionId() {
      bitField0_ = (bitField0_ & ~0x00000004);
      promotionId_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:cn.yscme.scrolling.auto.douyin.LiveShoppingMessage)
  }

  // @@protoc_insertion_point(class_scope:cn.yscme.scrolling.auto.douyin.LiveShoppingMessage)
  private static final cn.yscme.scrolling.auto.douyin.LiveShoppingMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new cn.yscme.scrolling.auto.douyin.LiveShoppingMessage();
  }

  public static cn.yscme.scrolling.auto.douyin.LiveShoppingMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<LiveShoppingMessage>
      PARSER = new com.google.protobuf.AbstractParser<LiveShoppingMessage>() {
    @java.lang.Override
    public LiveShoppingMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<LiveShoppingMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<LiveShoppingMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public cn.yscme.scrolling.auto.douyin.LiveShoppingMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

