// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: douyin.proto

// Protobuf Java Version: 3.25.1
package cn.yscme.scrolling.auto.douyin;

/**
 * Protobuf type {@code cn.yscme.scrolling.auto.douyin.NinePatchSetting}
 */
public final class NinePatchSetting extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:cn.yscme.scrolling.auto.douyin.NinePatchSetting)
        NinePatchSettingOrBuilder {
    private static final long serialVersionUID = 0L;

    // Use NinePatchSetting.newBuilder() to construct.
    private NinePatchSetting(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
    }

    private NinePatchSetting() {
        settingListList_ =
                com.google.protobuf.LazyStringArrayList.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
            UnusedPrivateParameter unused) {
        return new NinePatchSetting();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
        return cn.yscme.scrolling.auto.douyin.Douyin.internal_static_cn_yscme_scrolling_auto_douyin_NinePatchSetting_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
        return cn.yscme.scrolling.auto.douyin.Douyin.internal_static_cn_yscme_scrolling_auto_douyin_NinePatchSetting_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        cn.yscme.scrolling.auto.douyin.NinePatchSetting.class, cn.yscme.scrolling.auto.douyin.NinePatchSetting.Builder.class);
    }

    public static final int SETTINGLISTLIST_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private com.google.protobuf.LazyStringArrayList settingListList_ =
            com.google.protobuf.LazyStringArrayList.emptyList();

    /**
     * <code>repeated string settingListList = 1;</code>
     *
     * @return A list containing the settingListList.
     */
    public com.google.protobuf.ProtocolStringList
    getSettingListListList() {
        return settingListList_;
    }

    /**
     * <code>repeated string settingListList = 1;</code>
     *
     * @return The count of settingListList.
     */
    public int getSettingListListCount() {
        return settingListList_.size();
    }

    /**
     * <code>repeated string settingListList = 1;</code>
     *
     * @param index The index of the element to return.
     * @return The settingListList at the given index.
     */
    public java.lang.String getSettingListList(int index) {
        return settingListList_.get(index);
    }

    /**
     * <code>repeated string settingListList = 1;</code>
     *
     * @param index The index of the value to return.
     * @return The bytes of the settingListList at the given index.
     */
    public com.google.protobuf.ByteString
    getSettingListListBytes(int index) {
        return settingListList_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;

    @java.lang.Override
    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
        for (int i = 0; i < settingListList_.size(); i++) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 1, settingListList_.getRaw(i));
        }
        getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        {
            int dataSize = 0;
            for (int i = 0; i < settingListList_.size(); i++) {
                dataSize += computeStringSizeNoTag(settingListList_.getRaw(i));
            }
            size += dataSize;
            size += 1 * getSettingListListList().size();
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof cn.yscme.scrolling.auto.douyin.NinePatchSetting)) {
            return super.equals(obj);
        }
        cn.yscme.scrolling.auto.douyin.NinePatchSetting other = (cn.yscme.scrolling.auto.douyin.NinePatchSetting) obj;

        if (!getSettingListListList()
                .equals(other.getSettingListListList())) return false;
        if (!getUnknownFields().equals(other.getUnknownFields())) return false;
        return true;
    }

    @java.lang.Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (getSettingListListCount() > 0) {
            hash = (37 * hash) + SETTINGLISTLIST_FIELD_NUMBER;
            hash = (53 * hash) + getSettingListListList().hashCode();
        }
        hash = (29 * hash) + getUnknownFields().hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    public static cn.yscme.scrolling.auto.douyin.NinePatchSetting parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static cn.yscme.scrolling.auto.douyin.NinePatchSetting parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static cn.yscme.scrolling.auto.douyin.NinePatchSetting parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static cn.yscme.scrolling.auto.douyin.NinePatchSetting parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static cn.yscme.scrolling.auto.douyin.NinePatchSetting parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static cn.yscme.scrolling.auto.douyin.NinePatchSetting parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static cn.yscme.scrolling.auto.douyin.NinePatchSetting parseFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static cn.yscme.scrolling.auto.douyin.NinePatchSetting parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static cn.yscme.scrolling.auto.douyin.NinePatchSetting parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input);
    }

    public static cn.yscme.scrolling.auto.douyin.NinePatchSetting parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static cn.yscme.scrolling.auto.douyin.NinePatchSetting parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static cn.yscme.scrolling.auto.douyin.NinePatchSetting parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() {
        return newBuilder();
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(cn.yscme.scrolling.auto.douyin.NinePatchSetting prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @java.lang.Override
    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
                ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    /**
     * Protobuf type {@code cn.yscme.scrolling.auto.douyin.NinePatchSetting}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:cn.yscme.scrolling.auto.douyin.NinePatchSetting)
            cn.yscme.scrolling.auto.douyin.NinePatchSettingOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return cn.yscme.scrolling.auto.douyin.Douyin.internal_static_cn_yscme_scrolling_auto_douyin_NinePatchSetting_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return cn.yscme.scrolling.auto.douyin.Douyin.internal_static_cn_yscme_scrolling_auto_douyin_NinePatchSetting_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            cn.yscme.scrolling.auto.douyin.NinePatchSetting.class, cn.yscme.scrolling.auto.douyin.NinePatchSetting.Builder.class);
        }

        // Construct using cn.yscme.scrolling.auto.douyin.NinePatchSetting.newBuilder()
        private Builder() {

        }

        private Builder(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            super(parent);

        }

        @java.lang.Override
        public Builder clear() {
            super.clear();
            bitField0_ = 0;
            settingListList_ =
                    com.google.protobuf.LazyStringArrayList.emptyList();
            return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
            return cn.yscme.scrolling.auto.douyin.Douyin.internal_static_cn_yscme_scrolling_auto_douyin_NinePatchSetting_descriptor;
        }

        @java.lang.Override
        public cn.yscme.scrolling.auto.douyin.NinePatchSetting getDefaultInstanceForType() {
            return cn.yscme.scrolling.auto.douyin.NinePatchSetting.getDefaultInstance();
        }

        @java.lang.Override
        public cn.yscme.scrolling.auto.douyin.NinePatchSetting build() {
            cn.yscme.scrolling.auto.douyin.NinePatchSetting result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        @java.lang.Override
        public cn.yscme.scrolling.auto.douyin.NinePatchSetting buildPartial() {
            cn.yscme.scrolling.auto.douyin.NinePatchSetting result = new cn.yscme.scrolling.auto.douyin.NinePatchSetting(this);
            if (bitField0_ != 0) {
                buildPartial0(result);
            }
            onBuilt();
            return result;
        }

        private void buildPartial0(cn.yscme.scrolling.auto.douyin.NinePatchSetting result) {
            int from_bitField0_ = bitField0_;
            if (((from_bitField0_ & 0x00000001) != 0)) {
                settingListList_.makeImmutable();
                result.settingListList_ = settingListList_;
            }
        }

        @java.lang.Override
        public Builder clone() {
            return super.clone();
        }

        @java.lang.Override
        public Builder setField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                java.lang.Object value) {
            return super.setField(field, value);
        }

        @java.lang.Override
        public Builder clearField(
                com.google.protobuf.Descriptors.FieldDescriptor field) {
            return super.clearField(field);
        }

        @java.lang.Override
        public Builder clearOneof(
                com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return super.clearOneof(oneof);
        }

        @java.lang.Override
        public Builder setRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                int index, java.lang.Object value) {
            return super.setRepeatedField(field, index, value);
        }

        @java.lang.Override
        public Builder addRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                java.lang.Object value) {
            return super.addRepeatedField(field, value);
        }

        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof cn.yscme.scrolling.auto.douyin.NinePatchSetting) {
                return mergeFrom((cn.yscme.scrolling.auto.douyin.NinePatchSetting) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(cn.yscme.scrolling.auto.douyin.NinePatchSetting other) {
            if (other == cn.yscme.scrolling.auto.douyin.NinePatchSetting.getDefaultInstance()) return this;
            if (!other.settingListList_.isEmpty()) {
                if (settingListList_.isEmpty()) {
                    settingListList_ = other.settingListList_;
                    bitField0_ |= 0x00000001;
                } else {
                    ensureSettingListListIsMutable();
                    settingListList_.addAll(other.settingListList_);
                }
                onChanged();
            }
            this.mergeUnknownFields(other.getUnknownFields());
            onChanged();
            return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
            return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 10: {
                            java.lang.String s = input.readStringRequireUtf8();
                            ensureSettingListListIsMutable();
                            settingListList_.add(s);
                            break;
                        } // case 10
                        default: {
                            if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                                done = true; // was an endgroup tag
                            }
                            break;
                        } // default:
                    } // switch (tag)
                } // while (!done)
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.unwrapIOException();
            } finally {
                onChanged();
            } // finally
            return this;
        }

        private int bitField0_;

        private com.google.protobuf.LazyStringArrayList settingListList_ =
                com.google.protobuf.LazyStringArrayList.emptyList();

        private void ensureSettingListListIsMutable() {
            if (!settingListList_.isModifiable()) {
                settingListList_ = new com.google.protobuf.LazyStringArrayList(settingListList_);
            }
            bitField0_ |= 0x00000001;
        }

        /**
         * <code>repeated string settingListList = 1;</code>
         *
         * @return A list containing the settingListList.
         */
        public com.google.protobuf.ProtocolStringList
        getSettingListListList() {
            settingListList_.makeImmutable();
            return settingListList_;
        }

        /**
         * <code>repeated string settingListList = 1;</code>
         *
         * @return The count of settingListList.
         */
        public int getSettingListListCount() {
            return settingListList_.size();
        }

        /**
         * <code>repeated string settingListList = 1;</code>
         *
         * @param index The index of the element to return.
         * @return The settingListList at the given index.
         */
        public java.lang.String getSettingListList(int index) {
            return settingListList_.get(index);
        }

        /**
         * <code>repeated string settingListList = 1;</code>
         *
         * @param index The index of the value to return.
         * @return The bytes of the settingListList at the given index.
         */
        public com.google.protobuf.ByteString
        getSettingListListBytes(int index) {
            return settingListList_.getByteString(index);
        }

        /**
         * <code>repeated string settingListList = 1;</code>
         *
         * @param index The index to set the value at.
         * @param value The settingListList to set.
         * @return This builder for chaining.
         */
        public Builder setSettingListList(
                int index, java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }
            ensureSettingListListIsMutable();
            settingListList_.set(index, value);
            bitField0_ |= 0x00000001;
            onChanged();
            return this;
        }

        /**
         * <code>repeated string settingListList = 1;</code>
         *
         * @param value The settingListList to add.
         * @return This builder for chaining.
         */
        public Builder addSettingListList(
                java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }
            ensureSettingListListIsMutable();
            settingListList_.add(value);
            bitField0_ |= 0x00000001;
            onChanged();
            return this;
        }

        /**
         * <code>repeated string settingListList = 1;</code>
         *
         * @param values The settingListList to add.
         * @return This builder for chaining.
         */
        public Builder addAllSettingListList(
                java.lang.Iterable<java.lang.String> values) {
            ensureSettingListListIsMutable();
            com.google.protobuf.AbstractMessageLite.Builder.addAll(
                    values, settingListList_);
            bitField0_ |= 0x00000001;
            onChanged();
            return this;
        }

        /**
         * <code>repeated string settingListList = 1;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearSettingListList() {
            settingListList_ =
                    com.google.protobuf.LazyStringArrayList.emptyList();
            bitField0_ = (bitField0_ & ~0x00000001);
            ;
            onChanged();
            return this;
        }

        /**
         * <code>repeated string settingListList = 1;</code>
         *
         * @param value The bytes of the settingListList to add.
         * @return This builder for chaining.
         */
        public Builder addSettingListListBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);
            ensureSettingListListIsMutable();
            settingListList_.add(value);
            bitField0_ |= 0x00000001;
            onChanged();
            return this;
        }

        @java.lang.Override
        public final Builder setUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:cn.yscme.scrolling.auto.douyin.NinePatchSetting)
    }

    // @@protoc_insertion_point(class_scope:cn.yscme.scrolling.auto.douyin.NinePatchSetting)
    private static final cn.yscme.scrolling.auto.douyin.NinePatchSetting DEFAULT_INSTANCE;

    static {
        DEFAULT_INSTANCE = new cn.yscme.scrolling.auto.douyin.NinePatchSetting();
    }

    public static cn.yscme.scrolling.auto.douyin.NinePatchSetting getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<NinePatchSetting>
            PARSER = new com.google.protobuf.AbstractParser<NinePatchSetting>() {
        @java.lang.Override
        public NinePatchSetting parsePartialFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            Builder builder = newBuilder();
            try {
                builder.mergeFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(builder.buildPartial());
            } catch (com.google.protobuf.UninitializedMessageException e) {
                throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(e)
                        .setUnfinishedMessage(builder.buildPartial());
            }
            return builder.buildPartial();
        }
    };

    public static com.google.protobuf.Parser<NinePatchSetting> parser() {
        return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<NinePatchSetting> getParserForType() {
        return PARSER;
    }

    @java.lang.Override
    public cn.yscme.scrolling.auto.douyin.NinePatchSetting getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }

}

