// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: douyin.proto

// Protobuf Java Version: 3.25.1
package cn.yscme.scrolling.auto.douyin;

/**
 * <pre>
 * from https://github.com/scx567888/live-room-watcher/blob/master/src/main/proto/douyin_hack/webcast/im/RoomMessage.proto
 * </pre>
 * <p>
 * Protobuf type {@code cn.yscme.scrolling.auto.douyin.RoomMessage}
 */
public final class RoomMessage extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:cn.yscme.scrolling.auto.douyin.RoomMessage)
        RoomMessageOrBuilder {
    private static final long serialVersionUID = 0L;

    // Use RoomMessage.newBuilder() to construct.
    private RoomMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
    }

    private RoomMessage() {
        content_ = "";
        roommessagetype_ = 0;
        bizScene_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
            UnusedPrivateParameter unused) {
        return new RoomMessage();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
        return cn.yscme.scrolling.auto.douyin.Douyin.internal_static_cn_yscme_scrolling_auto_douyin_RoomMessage_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
            int number) {
        switch (number) {
            case 30:
                return internalGetBuriedPointMap();
            default:
                throw new RuntimeException(
                        "Invalid map field number: " + number);
        }
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
        return cn.yscme.scrolling.auto.douyin.Douyin.internal_static_cn_yscme_scrolling_auto_douyin_RoomMessage_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        cn.yscme.scrolling.auto.douyin.RoomMessage.class, cn.yscme.scrolling.auto.douyin.RoomMessage.Builder.class);
    }

    private int bitField0_;
    public static final int COMMON_FIELD_NUMBER = 1;
    private cn.yscme.scrolling.auto.douyin.Common common_;

    /**
     * <code>.cn.yscme.scrolling.auto.douyin.Common common = 1;</code>
     *
     * @return Whether the common field is set.
     */
    @java.lang.Override
    public boolean hasCommon() {
        return ((bitField0_ & 0x00000001) != 0);
    }

    /**
     * <code>.cn.yscme.scrolling.auto.douyin.Common common = 1;</code>
     *
     * @return The common.
     */
    @java.lang.Override
    public cn.yscme.scrolling.auto.douyin.Common getCommon() {
        return common_ == null ? cn.yscme.scrolling.auto.douyin.Common.getDefaultInstance() : common_;
    }

    /**
     * <code>.cn.yscme.scrolling.auto.douyin.Common common = 1;</code>
     */
    @java.lang.Override
    public cn.yscme.scrolling.auto.douyin.CommonOrBuilder getCommonOrBuilder() {
        return common_ == null ? cn.yscme.scrolling.auto.douyin.Common.getDefaultInstance() : common_;
    }

    public static final int CONTENT_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object content_ = "";

    /**
     * <code>string content = 2;</code>
     *
     * @return The content.
     */
    @java.lang.Override
    public java.lang.String getContent() {
        java.lang.Object ref = content_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            content_ = s;
            return s;
        }
    }

    /**
     * <code>string content = 2;</code>
     *
     * @return The bytes for content.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
    getContentBytes() {
        java.lang.Object ref = content_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
            content_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public static final int SUPPROTLANDSCAPE_FIELD_NUMBER = 3;
    private boolean supprotLandscape_ = false;

    /**
     * <code>bool supprotLandscape = 3;</code>
     *
     * @return The supprotLandscape.
     */
    @java.lang.Override
    public boolean getSupprotLandscape() {
        return supprotLandscape_;
    }

    public static final int ROOMMESSAGETYPE_FIELD_NUMBER = 4;
    private int roommessagetype_ = 0;

    /**
     * <code>.cn.yscme.scrolling.auto.douyin.RoomMsgTypeEnum roommessagetype = 4;</code>
     *
     * @return The enum numeric value on the wire for roommessagetype.
     */
    @java.lang.Override
    public int getRoommessagetypeValue() {
        return roommessagetype_;
    }

    /**
     * <code>.cn.yscme.scrolling.auto.douyin.RoomMsgTypeEnum roommessagetype = 4;</code>
     *
     * @return The roommessagetype.
     */
    @java.lang.Override
    public cn.yscme.scrolling.auto.douyin.RoomMsgTypeEnum getRoommessagetype() {
        cn.yscme.scrolling.auto.douyin.RoomMsgTypeEnum result = cn.yscme.scrolling.auto.douyin.RoomMsgTypeEnum.forNumber(roommessagetype_);
        return result == null ? cn.yscme.scrolling.auto.douyin.RoomMsgTypeEnum.UNRECOGNIZED : result;
    }

    public static final int SYSTEMTOPMSG_FIELD_NUMBER = 5;
    private boolean systemTopMsg_ = false;

    /**
     * <code>bool systemTopMsg = 5;</code>
     *
     * @return The systemTopMsg.
     */
    @java.lang.Override
    public boolean getSystemTopMsg() {
        return systemTopMsg_;
    }

    public static final int FORCEDGUARANTEE_FIELD_NUMBER = 6;
    private boolean forcedGuarantee_ = false;

    /**
     * <code>bool forcedGuarantee = 6;</code>
     *
     * @return The forcedGuarantee.
     */
    @java.lang.Override
    public boolean getForcedGuarantee() {
        return forcedGuarantee_;
    }

    public static final int BIZSCENE_FIELD_NUMBER = 20;
    @SuppressWarnings("serial")
    private volatile java.lang.Object bizScene_ = "";

    /**
     * <code>string bizScene = 20;</code>
     *
     * @return The bizScene.
     */
    @java.lang.Override
    public java.lang.String getBizScene() {
        java.lang.Object ref = bizScene_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            bizScene_ = s;
            return s;
        }
    }

    /**
     * <code>string bizScene = 20;</code>
     *
     * @return The bytes for bizScene.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
    getBizSceneBytes() {
        java.lang.Object ref = bizScene_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
            bizScene_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public static final int BURIEDPOINTMAP_FIELD_NUMBER = 30;

    private static final class BuriedPointMapDefaultEntryHolder {
        static final com.google.protobuf.MapEntry<
                java.lang.String, java.lang.String> defaultEntry =
                com.google.protobuf.MapEntry
                        .<java.lang.String, java.lang.String>newDefaultInstance(
                                cn.yscme.scrolling.auto.douyin.Douyin.internal_static_cn_yscme_scrolling_auto_douyin_RoomMessage_BuriedPointMapEntry_descriptor,
                                com.google.protobuf.WireFormat.FieldType.STRING,
                                "",
                                com.google.protobuf.WireFormat.FieldType.STRING,
                                "");
    }

    @SuppressWarnings("serial")
    private com.google.protobuf.MapField<
            java.lang.String, java.lang.String> buriedPointMap_;

    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetBuriedPointMap() {
        if (buriedPointMap_ == null) {
            return com.google.protobuf.MapField.emptyMapField(
                    BuriedPointMapDefaultEntryHolder.defaultEntry);
        }
        return buriedPointMap_;
    }

    public int getBuriedPointMapCount() {
        return internalGetBuriedPointMap().getMap().size();
    }

    /**
     * <code>map&lt;string, string&gt; buriedPointMap = 30;</code>
     */
    @java.lang.Override
    public boolean containsBuriedPointMap(
            java.lang.String key) {
        if (key == null) {
            throw new NullPointerException("map key");
        }
        return internalGetBuriedPointMap().getMap().containsKey(key);
    }

    /**
     * Use {@link #getBuriedPointMapMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getBuriedPointMap() {
        return getBuriedPointMapMap();
    }

    /**
     * <code>map&lt;string, string&gt; buriedPointMap = 30;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, java.lang.String> getBuriedPointMapMap() {
        return internalGetBuriedPointMap().getMap();
    }

    /**
     * <code>map&lt;string, string&gt; buriedPointMap = 30;</code>
     */
    @java.lang.Override
    public /* nullable */
    java.lang.String getBuriedPointMapOrDefault(
            java.lang.String key,
            /* nullable */
            java.lang.String defaultValue) {
        if (key == null) {
            throw new NullPointerException("map key");
        }
        java.util.Map<java.lang.String, java.lang.String> map =
                internalGetBuriedPointMap().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
    }

    /**
     * <code>map&lt;string, string&gt; buriedPointMap = 30;</code>
     */
    @java.lang.Override
    public java.lang.String getBuriedPointMapOrThrow(
            java.lang.String key) {
        if (key == null) {
            throw new NullPointerException("map key");
        }
        java.util.Map<java.lang.String, java.lang.String> map =
                internalGetBuriedPointMap().getMap();
        if (!map.containsKey(key)) {
            throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
    }

    private byte memoizedIsInitialized = -1;

    @java.lang.Override
    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
        if (((bitField0_ & 0x00000001) != 0)) {
            output.writeMessage(1, getCommon());
        }
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(content_)) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 2, content_);
        }
        if (supprotLandscape_ != false) {
            output.writeBool(3, supprotLandscape_);
        }
        if (roommessagetype_ != cn.yscme.scrolling.auto.douyin.RoomMsgTypeEnum.DEFAULTROOMMSG.getNumber()) {
            output.writeEnum(4, roommessagetype_);
        }
        if (systemTopMsg_ != false) {
            output.writeBool(5, systemTopMsg_);
        }
        if (forcedGuarantee_ != false) {
            output.writeBool(6, forcedGuarantee_);
        }
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(bizScene_)) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 20, bizScene_);
        }
        com.google.protobuf.GeneratedMessageV3
                .serializeStringMapTo(
                        output,
                        internalGetBuriedPointMap(),
                        BuriedPointMapDefaultEntryHolder.defaultEntry,
                        30);
        getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) != 0)) {
            size += com.google.protobuf.CodedOutputStream
                    .computeMessageSize(1, getCommon());
        }
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(content_)) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, content_);
        }
        if (supprotLandscape_ != false) {
            size += com.google.protobuf.CodedOutputStream
                    .computeBoolSize(3, supprotLandscape_);
        }
        if (roommessagetype_ != cn.yscme.scrolling.auto.douyin.RoomMsgTypeEnum.DEFAULTROOMMSG.getNumber()) {
            size += com.google.protobuf.CodedOutputStream
                    .computeEnumSize(4, roommessagetype_);
        }
        if (systemTopMsg_ != false) {
            size += com.google.protobuf.CodedOutputStream
                    .computeBoolSize(5, systemTopMsg_);
        }
        if (forcedGuarantee_ != false) {
            size += com.google.protobuf.CodedOutputStream
                    .computeBoolSize(6, forcedGuarantee_);
        }
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(bizScene_)) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(20, bizScene_);
        }
        for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
                : internalGetBuriedPointMap().getMap().entrySet()) {
            com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
                    buriedPointMap__ = BuriedPointMapDefaultEntryHolder.defaultEntry.newBuilderForType()
                    .setKey(entry.getKey())
                    .setValue(entry.getValue())
                    .build();
            size += com.google.protobuf.CodedOutputStream
                    .computeMessageSize(30, buriedPointMap__);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof cn.yscme.scrolling.auto.douyin.RoomMessage)) {
            return super.equals(obj);
        }
        cn.yscme.scrolling.auto.douyin.RoomMessage other = (cn.yscme.scrolling.auto.douyin.RoomMessage) obj;

        if (hasCommon() != other.hasCommon()) return false;
        if (hasCommon()) {
            if (!getCommon()
                    .equals(other.getCommon())) return false;
        }
        if (!getContent()
                .equals(other.getContent())) return false;
        if (getSupprotLandscape()
                != other.getSupprotLandscape()) return false;
        if (roommessagetype_ != other.roommessagetype_) return false;
        if (getSystemTopMsg()
                != other.getSystemTopMsg()) return false;
        if (getForcedGuarantee()
                != other.getForcedGuarantee()) return false;
        if (!getBizScene()
                .equals(other.getBizScene())) return false;
        if (!internalGetBuriedPointMap().equals(
                other.internalGetBuriedPointMap())) return false;
        if (!getUnknownFields().equals(other.getUnknownFields())) return false;
        return true;
    }

    @java.lang.Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (hasCommon()) {
            hash = (37 * hash) + COMMON_FIELD_NUMBER;
            hash = (53 * hash) + getCommon().hashCode();
        }
        hash = (37 * hash) + CONTENT_FIELD_NUMBER;
        hash = (53 * hash) + getContent().hashCode();
        hash = (37 * hash) + SUPPROTLANDSCAPE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
                getSupprotLandscape());
        hash = (37 * hash) + ROOMMESSAGETYPE_FIELD_NUMBER;
        hash = (53 * hash) + roommessagetype_;
        hash = (37 * hash) + SYSTEMTOPMSG_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
                getSystemTopMsg());
        hash = (37 * hash) + FORCEDGUARANTEE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
                getForcedGuarantee());
        hash = (37 * hash) + BIZSCENE_FIELD_NUMBER;
        hash = (53 * hash) + getBizScene().hashCode();
        if (!internalGetBuriedPointMap().getMap().isEmpty()) {
            hash = (37 * hash) + BURIEDPOINTMAP_FIELD_NUMBER;
            hash = (53 * hash) + internalGetBuriedPointMap().hashCode();
        }
        hash = (29 * hash) + getUnknownFields().hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    public static cn.yscme.scrolling.auto.douyin.RoomMessage parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static cn.yscme.scrolling.auto.douyin.RoomMessage parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static cn.yscme.scrolling.auto.douyin.RoomMessage parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static cn.yscme.scrolling.auto.douyin.RoomMessage parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static cn.yscme.scrolling.auto.douyin.RoomMessage parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static cn.yscme.scrolling.auto.douyin.RoomMessage parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static cn.yscme.scrolling.auto.douyin.RoomMessage parseFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static cn.yscme.scrolling.auto.douyin.RoomMessage parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static cn.yscme.scrolling.auto.douyin.RoomMessage parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input);
    }

    public static cn.yscme.scrolling.auto.douyin.RoomMessage parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static cn.yscme.scrolling.auto.douyin.RoomMessage parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static cn.yscme.scrolling.auto.douyin.RoomMessage parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() {
        return newBuilder();
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(cn.yscme.scrolling.auto.douyin.RoomMessage prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @java.lang.Override
    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
                ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    /**
     * <pre>
     * from https://github.com/scx567888/live-room-watcher/blob/master/src/main/proto/douyin_hack/webcast/im/RoomMessage.proto
     * </pre>
     * <p>
     * Protobuf type {@code cn.yscme.scrolling.auto.douyin.RoomMessage}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:cn.yscme.scrolling.auto.douyin.RoomMessage)
            cn.yscme.scrolling.auto.douyin.RoomMessageOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return cn.yscme.scrolling.auto.douyin.Douyin.internal_static_cn_yscme_scrolling_auto_douyin_RoomMessage_descriptor;
        }

        @SuppressWarnings({"rawtypes"})
        protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
                int number) {
            switch (number) {
                case 30:
                    return internalGetBuriedPointMap();
                default:
                    throw new RuntimeException(
                            "Invalid map field number: " + number);
            }
        }

        @SuppressWarnings({"rawtypes"})
        protected com.google.protobuf.MapFieldReflectionAccessor internalGetMutableMapFieldReflection(
                int number) {
            switch (number) {
                case 30:
                    return internalGetMutableBuriedPointMap();
                default:
                    throw new RuntimeException(
                            "Invalid map field number: " + number);
            }
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return cn.yscme.scrolling.auto.douyin.Douyin.internal_static_cn_yscme_scrolling_auto_douyin_RoomMessage_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            cn.yscme.scrolling.auto.douyin.RoomMessage.class, cn.yscme.scrolling.auto.douyin.RoomMessage.Builder.class);
        }

        // Construct using cn.yscme.scrolling.auto.douyin.RoomMessage.newBuilder()
        private Builder() {
            maybeForceBuilderInitialization();
        }

        private Builder(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
        }

        private void maybeForceBuilderInitialization() {
            if (com.google.protobuf.GeneratedMessageV3
                    .alwaysUseFieldBuilders) {
                getCommonFieldBuilder();
            }
        }

        @java.lang.Override
        public Builder clear() {
            super.clear();
            bitField0_ = 0;
            common_ = null;
            if (commonBuilder_ != null) {
                commonBuilder_.dispose();
                commonBuilder_ = null;
            }
            content_ = "";
            supprotLandscape_ = false;
            roommessagetype_ = 0;
            systemTopMsg_ = false;
            forcedGuarantee_ = false;
            bizScene_ = "";
            internalGetMutableBuriedPointMap().clear();
            return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
            return cn.yscme.scrolling.auto.douyin.Douyin.internal_static_cn_yscme_scrolling_auto_douyin_RoomMessage_descriptor;
        }

        @java.lang.Override
        public cn.yscme.scrolling.auto.douyin.RoomMessage getDefaultInstanceForType() {
            return cn.yscme.scrolling.auto.douyin.RoomMessage.getDefaultInstance();
        }

        @java.lang.Override
        public cn.yscme.scrolling.auto.douyin.RoomMessage build() {
            cn.yscme.scrolling.auto.douyin.RoomMessage result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        @java.lang.Override
        public cn.yscme.scrolling.auto.douyin.RoomMessage buildPartial() {
            cn.yscme.scrolling.auto.douyin.RoomMessage result = new cn.yscme.scrolling.auto.douyin.RoomMessage(this);
            if (bitField0_ != 0) {
                buildPartial0(result);
            }
            onBuilt();
            return result;
        }

        private void buildPartial0(cn.yscme.scrolling.auto.douyin.RoomMessage result) {
            int from_bitField0_ = bitField0_;
            int to_bitField0_ = 0;
            if (((from_bitField0_ & 0x00000001) != 0)) {
                result.common_ = commonBuilder_ == null
                        ? common_
                        : commonBuilder_.build();
                to_bitField0_ |= 0x00000001;
            }
            if (((from_bitField0_ & 0x00000002) != 0)) {
                result.content_ = content_;
            }
            if (((from_bitField0_ & 0x00000004) != 0)) {
                result.supprotLandscape_ = supprotLandscape_;
            }
            if (((from_bitField0_ & 0x00000008) != 0)) {
                result.roommessagetype_ = roommessagetype_;
            }
            if (((from_bitField0_ & 0x00000010) != 0)) {
                result.systemTopMsg_ = systemTopMsg_;
            }
            if (((from_bitField0_ & 0x00000020) != 0)) {
                result.forcedGuarantee_ = forcedGuarantee_;
            }
            if (((from_bitField0_ & 0x00000040) != 0)) {
                result.bizScene_ = bizScene_;
            }
            if (((from_bitField0_ & 0x00000080) != 0)) {
                result.buriedPointMap_ = internalGetBuriedPointMap();
                result.buriedPointMap_.makeImmutable();
            }
            result.bitField0_ |= to_bitField0_;
        }

        @java.lang.Override
        public Builder clone() {
            return super.clone();
        }

        @java.lang.Override
        public Builder setField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                java.lang.Object value) {
            return super.setField(field, value);
        }

        @java.lang.Override
        public Builder clearField(
                com.google.protobuf.Descriptors.FieldDescriptor field) {
            return super.clearField(field);
        }

        @java.lang.Override
        public Builder clearOneof(
                com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return super.clearOneof(oneof);
        }

        @java.lang.Override
        public Builder setRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                int index, java.lang.Object value) {
            return super.setRepeatedField(field, index, value);
        }

        @java.lang.Override
        public Builder addRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                java.lang.Object value) {
            return super.addRepeatedField(field, value);
        }

        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof cn.yscme.scrolling.auto.douyin.RoomMessage) {
                return mergeFrom((cn.yscme.scrolling.auto.douyin.RoomMessage) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(cn.yscme.scrolling.auto.douyin.RoomMessage other) {
            if (other == cn.yscme.scrolling.auto.douyin.RoomMessage.getDefaultInstance()) return this;
            if (other.hasCommon()) {
                mergeCommon(other.getCommon());
            }
            if (!other.getContent().isEmpty()) {
                content_ = other.content_;
                bitField0_ |= 0x00000002;
                onChanged();
            }
            if (other.getSupprotLandscape() != false) {
                setSupprotLandscape(other.getSupprotLandscape());
            }
            if (other.roommessagetype_ != 0) {
                setRoommessagetypeValue(other.getRoommessagetypeValue());
            }
            if (other.getSystemTopMsg() != false) {
                setSystemTopMsg(other.getSystemTopMsg());
            }
            if (other.getForcedGuarantee() != false) {
                setForcedGuarantee(other.getForcedGuarantee());
            }
            if (!other.getBizScene().isEmpty()) {
                bizScene_ = other.bizScene_;
                bitField0_ |= 0x00000040;
                onChanged();
            }
            internalGetMutableBuriedPointMap().mergeFrom(
                    other.internalGetBuriedPointMap());
            bitField0_ |= 0x00000080;
            this.mergeUnknownFields(other.getUnknownFields());
            onChanged();
            return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
            return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 10: {
                            input.readMessage(
                                    getCommonFieldBuilder().getBuilder(),
                                    extensionRegistry);
                            bitField0_ |= 0x00000001;
                            break;
                        } // case 10
                        case 18: {
                            content_ = input.readStringRequireUtf8();
                            bitField0_ |= 0x00000002;
                            break;
                        } // case 18
                        case 24: {
                            supprotLandscape_ = input.readBool();
                            bitField0_ |= 0x00000004;
                            break;
                        } // case 24
                        case 32: {
                            roommessagetype_ = input.readEnum();
                            bitField0_ |= 0x00000008;
                            break;
                        } // case 32
                        case 40: {
                            systemTopMsg_ = input.readBool();
                            bitField0_ |= 0x00000010;
                            break;
                        } // case 40
                        case 48: {
                            forcedGuarantee_ = input.readBool();
                            bitField0_ |= 0x00000020;
                            break;
                        } // case 48
                        case 162: {
                            bizScene_ = input.readStringRequireUtf8();
                            bitField0_ |= 0x00000040;
                            break;
                        } // case 162
                        case 242: {
                            com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
                                    buriedPointMap__ = input.readMessage(
                                    BuriedPointMapDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
                            internalGetMutableBuriedPointMap().getMutableMap().put(
                                    buriedPointMap__.getKey(), buriedPointMap__.getValue());
                            bitField0_ |= 0x00000080;
                            break;
                        } // case 242
                        default: {
                            if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                                done = true; // was an endgroup tag
                            }
                            break;
                        } // default:
                    } // switch (tag)
                } // while (!done)
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.unwrapIOException();
            } finally {
                onChanged();
            } // finally
            return this;
        }

        private int bitField0_;

        private cn.yscme.scrolling.auto.douyin.Common common_;
        private com.google.protobuf.SingleFieldBuilderV3<
                cn.yscme.scrolling.auto.douyin.Common, cn.yscme.scrolling.auto.douyin.Common.Builder, cn.yscme.scrolling.auto.douyin.CommonOrBuilder> commonBuilder_;

        /**
         * <code>.cn.yscme.scrolling.auto.douyin.Common common = 1;</code>
         *
         * @return Whether the common field is set.
         */
        public boolean hasCommon() {
            return ((bitField0_ & 0x00000001) != 0);
        }

        /**
         * <code>.cn.yscme.scrolling.auto.douyin.Common common = 1;</code>
         *
         * @return The common.
         */
        public cn.yscme.scrolling.auto.douyin.Common getCommon() {
            if (commonBuilder_ == null) {
                return common_ == null ? cn.yscme.scrolling.auto.douyin.Common.getDefaultInstance() : common_;
            } else {
                return commonBuilder_.getMessage();
            }
        }

        /**
         * <code>.cn.yscme.scrolling.auto.douyin.Common common = 1;</code>
         */
        public Builder setCommon(cn.yscme.scrolling.auto.douyin.Common value) {
            if (commonBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                common_ = value;
            } else {
                commonBuilder_.setMessage(value);
            }
            bitField0_ |= 0x00000001;
            onChanged();
            return this;
        }

        /**
         * <code>.cn.yscme.scrolling.auto.douyin.Common common = 1;</code>
         */
        public Builder setCommon(
                cn.yscme.scrolling.auto.douyin.Common.Builder builderForValue) {
            if (commonBuilder_ == null) {
                common_ = builderForValue.build();
            } else {
                commonBuilder_.setMessage(builderForValue.build());
            }
            bitField0_ |= 0x00000001;
            onChanged();
            return this;
        }

        /**
         * <code>.cn.yscme.scrolling.auto.douyin.Common common = 1;</code>
         */
        public Builder mergeCommon(cn.yscme.scrolling.auto.douyin.Common value) {
            if (commonBuilder_ == null) {
                if (((bitField0_ & 0x00000001) != 0) &&
                        common_ != null &&
                        common_ != cn.yscme.scrolling.auto.douyin.Common.getDefaultInstance()) {
                    getCommonBuilder().mergeFrom(value);
                } else {
                    common_ = value;
                }
            } else {
                commonBuilder_.mergeFrom(value);
            }
            if (common_ != null) {
                bitField0_ |= 0x00000001;
                onChanged();
            }
            return this;
        }

        /**
         * <code>.cn.yscme.scrolling.auto.douyin.Common common = 1;</code>
         */
        public Builder clearCommon() {
            bitField0_ = (bitField0_ & ~0x00000001);
            common_ = null;
            if (commonBuilder_ != null) {
                commonBuilder_.dispose();
                commonBuilder_ = null;
            }
            onChanged();
            return this;
        }

        /**
         * <code>.cn.yscme.scrolling.auto.douyin.Common common = 1;</code>
         */
        public cn.yscme.scrolling.auto.douyin.Common.Builder getCommonBuilder() {
            bitField0_ |= 0x00000001;
            onChanged();
            return getCommonFieldBuilder().getBuilder();
        }

        /**
         * <code>.cn.yscme.scrolling.auto.douyin.Common common = 1;</code>
         */
        public cn.yscme.scrolling.auto.douyin.CommonOrBuilder getCommonOrBuilder() {
            if (commonBuilder_ != null) {
                return commonBuilder_.getMessageOrBuilder();
            } else {
                return common_ == null ?
                        cn.yscme.scrolling.auto.douyin.Common.getDefaultInstance() : common_;
            }
        }

        /**
         * <code>.cn.yscme.scrolling.auto.douyin.Common common = 1;</code>
         */
        private com.google.protobuf.SingleFieldBuilderV3<
                cn.yscme.scrolling.auto.douyin.Common, cn.yscme.scrolling.auto.douyin.Common.Builder, cn.yscme.scrolling.auto.douyin.CommonOrBuilder>
        getCommonFieldBuilder() {
            if (commonBuilder_ == null) {
                commonBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                        cn.yscme.scrolling.auto.douyin.Common, cn.yscme.scrolling.auto.douyin.Common.Builder, cn.yscme.scrolling.auto.douyin.CommonOrBuilder>(
                        getCommon(),
                        getParentForChildren(),
                        isClean());
                common_ = null;
            }
            return commonBuilder_;
        }

        private java.lang.Object content_ = "";

        /**
         * <code>string content = 2;</code>
         *
         * @return The content.
         */
        public java.lang.String getContent() {
            java.lang.Object ref = content_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                content_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <code>string content = 2;</code>
         *
         * @return The bytes for content.
         */
        public com.google.protobuf.ByteString
        getContentBytes() {
            java.lang.Object ref = content_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                content_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string content = 2;</code>
         *
         * @param value The content to set.
         * @return This builder for chaining.
         */
        public Builder setContent(
                java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }
            content_ = value;
            bitField0_ |= 0x00000002;
            onChanged();
            return this;
        }

        /**
         * <code>string content = 2;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearContent() {
            content_ = getDefaultInstance().getContent();
            bitField0_ = (bitField0_ & ~0x00000002);
            onChanged();
            return this;
        }

        /**
         * <code>string content = 2;</code>
         *
         * @param value The bytes for content to set.
         * @return This builder for chaining.
         */
        public Builder setContentBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);
            content_ = value;
            bitField0_ |= 0x00000002;
            onChanged();
            return this;
        }

        private boolean supprotLandscape_;

        /**
         * <code>bool supprotLandscape = 3;</code>
         *
         * @return The supprotLandscape.
         */
        @java.lang.Override
        public boolean getSupprotLandscape() {
            return supprotLandscape_;
        }

        /**
         * <code>bool supprotLandscape = 3;</code>
         *
         * @param value The supprotLandscape to set.
         * @return This builder for chaining.
         */
        public Builder setSupprotLandscape(boolean value) {

            supprotLandscape_ = value;
            bitField0_ |= 0x00000004;
            onChanged();
            return this;
        }

        /**
         * <code>bool supprotLandscape = 3;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearSupprotLandscape() {
            bitField0_ = (bitField0_ & ~0x00000004);
            supprotLandscape_ = false;
            onChanged();
            return this;
        }

        private int roommessagetype_ = 0;

        /**
         * <code>.cn.yscme.scrolling.auto.douyin.RoomMsgTypeEnum roommessagetype = 4;</code>
         *
         * @return The enum numeric value on the wire for roommessagetype.
         */
        @java.lang.Override
        public int getRoommessagetypeValue() {
            return roommessagetype_;
        }

        /**
         * <code>.cn.yscme.scrolling.auto.douyin.RoomMsgTypeEnum roommessagetype = 4;</code>
         *
         * @param value The enum numeric value on the wire for roommessagetype to set.
         * @return This builder for chaining.
         */
        public Builder setRoommessagetypeValue(int value) {
            roommessagetype_ = value;
            bitField0_ |= 0x00000008;
            onChanged();
            return this;
        }

        /**
         * <code>.cn.yscme.scrolling.auto.douyin.RoomMsgTypeEnum roommessagetype = 4;</code>
         *
         * @return The roommessagetype.
         */
        @java.lang.Override
        public cn.yscme.scrolling.auto.douyin.RoomMsgTypeEnum getRoommessagetype() {
            cn.yscme.scrolling.auto.douyin.RoomMsgTypeEnum result = cn.yscme.scrolling.auto.douyin.RoomMsgTypeEnum.forNumber(roommessagetype_);
            return result == null ? cn.yscme.scrolling.auto.douyin.RoomMsgTypeEnum.UNRECOGNIZED : result;
        }

        /**
         * <code>.cn.yscme.scrolling.auto.douyin.RoomMsgTypeEnum roommessagetype = 4;</code>
         *
         * @param value The roommessagetype to set.
         * @return This builder for chaining.
         */
        public Builder setRoommessagetype(cn.yscme.scrolling.auto.douyin.RoomMsgTypeEnum value) {
            if (value == null) {
                throw new NullPointerException();
            }
            bitField0_ |= 0x00000008;
            roommessagetype_ = value.getNumber();
            onChanged();
            return this;
        }

        /**
         * <code>.cn.yscme.scrolling.auto.douyin.RoomMsgTypeEnum roommessagetype = 4;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearRoommessagetype() {
            bitField0_ = (bitField0_ & ~0x00000008);
            roommessagetype_ = 0;
            onChanged();
            return this;
        }

        private boolean systemTopMsg_;

        /**
         * <code>bool systemTopMsg = 5;</code>
         *
         * @return The systemTopMsg.
         */
        @java.lang.Override
        public boolean getSystemTopMsg() {
            return systemTopMsg_;
        }

        /**
         * <code>bool systemTopMsg = 5;</code>
         *
         * @param value The systemTopMsg to set.
         * @return This builder for chaining.
         */
        public Builder setSystemTopMsg(boolean value) {

            systemTopMsg_ = value;
            bitField0_ |= 0x00000010;
            onChanged();
            return this;
        }

        /**
         * <code>bool systemTopMsg = 5;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearSystemTopMsg() {
            bitField0_ = (bitField0_ & ~0x00000010);
            systemTopMsg_ = false;
            onChanged();
            return this;
        }

        private boolean forcedGuarantee_;

        /**
         * <code>bool forcedGuarantee = 6;</code>
         *
         * @return The forcedGuarantee.
         */
        @java.lang.Override
        public boolean getForcedGuarantee() {
            return forcedGuarantee_;
        }

        /**
         * <code>bool forcedGuarantee = 6;</code>
         *
         * @param value The forcedGuarantee to set.
         * @return This builder for chaining.
         */
        public Builder setForcedGuarantee(boolean value) {

            forcedGuarantee_ = value;
            bitField0_ |= 0x00000020;
            onChanged();
            return this;
        }

        /**
         * <code>bool forcedGuarantee = 6;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearForcedGuarantee() {
            bitField0_ = (bitField0_ & ~0x00000020);
            forcedGuarantee_ = false;
            onChanged();
            return this;
        }

        private java.lang.Object bizScene_ = "";

        /**
         * <code>string bizScene = 20;</code>
         *
         * @return The bizScene.
         */
        public java.lang.String getBizScene() {
            java.lang.Object ref = bizScene_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                bizScene_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <code>string bizScene = 20;</code>
         *
         * @return The bytes for bizScene.
         */
        public com.google.protobuf.ByteString
        getBizSceneBytes() {
            java.lang.Object ref = bizScene_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                bizScene_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string bizScene = 20;</code>
         *
         * @param value The bizScene to set.
         * @return This builder for chaining.
         */
        public Builder setBizScene(
                java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }
            bizScene_ = value;
            bitField0_ |= 0x00000040;
            onChanged();
            return this;
        }

        /**
         * <code>string bizScene = 20;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearBizScene() {
            bizScene_ = getDefaultInstance().getBizScene();
            bitField0_ = (bitField0_ & ~0x00000040);
            onChanged();
            return this;
        }

        /**
         * <code>string bizScene = 20;</code>
         *
         * @param value The bytes for bizScene to set.
         * @return This builder for chaining.
         */
        public Builder setBizSceneBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);
            bizScene_ = value;
            bitField0_ |= 0x00000040;
            onChanged();
            return this;
        }

        private com.google.protobuf.MapField<
                java.lang.String, java.lang.String> buriedPointMap_;

        private com.google.protobuf.MapField<java.lang.String, java.lang.String>
        internalGetBuriedPointMap() {
            if (buriedPointMap_ == null) {
                return com.google.protobuf.MapField.emptyMapField(
                        BuriedPointMapDefaultEntryHolder.defaultEntry);
            }
            return buriedPointMap_;
        }

        private com.google.protobuf.MapField<java.lang.String, java.lang.String>
        internalGetMutableBuriedPointMap() {
            if (buriedPointMap_ == null) {
                buriedPointMap_ = com.google.protobuf.MapField.newMapField(
                        BuriedPointMapDefaultEntryHolder.defaultEntry);
            }
            if (!buriedPointMap_.isMutable()) {
                buriedPointMap_ = buriedPointMap_.copy();
            }
            bitField0_ |= 0x00000080;
            onChanged();
            return buriedPointMap_;
        }

        public int getBuriedPointMapCount() {
            return internalGetBuriedPointMap().getMap().size();
        }

        /**
         * <code>map&lt;string, string&gt; buriedPointMap = 30;</code>
         */
        @java.lang.Override
        public boolean containsBuriedPointMap(
                java.lang.String key) {
            if (key == null) {
                throw new NullPointerException("map key");
            }
            return internalGetBuriedPointMap().getMap().containsKey(key);
        }

        /**
         * Use {@link #getBuriedPointMapMap()} instead.
         */
        @java.lang.Override
        @java.lang.Deprecated
        public java.util.Map<java.lang.String, java.lang.String> getBuriedPointMap() {
            return getBuriedPointMapMap();
        }

        /**
         * <code>map&lt;string, string&gt; buriedPointMap = 30;</code>
         */
        @java.lang.Override
        public java.util.Map<java.lang.String, java.lang.String> getBuriedPointMapMap() {
            return internalGetBuriedPointMap().getMap();
        }

        /**
         * <code>map&lt;string, string&gt; buriedPointMap = 30;</code>
         */
        @java.lang.Override
        public /* nullable */
        java.lang.String getBuriedPointMapOrDefault(
                java.lang.String key,
                /* nullable */
                java.lang.String defaultValue) {
            if (key == null) {
                throw new NullPointerException("map key");
            }
            java.util.Map<java.lang.String, java.lang.String> map =
                    internalGetBuriedPointMap().getMap();
            return map.containsKey(key) ? map.get(key) : defaultValue;
        }

        /**
         * <code>map&lt;string, string&gt; buriedPointMap = 30;</code>
         */
        @java.lang.Override
        public java.lang.String getBuriedPointMapOrThrow(
                java.lang.String key) {
            if (key == null) {
                throw new NullPointerException("map key");
            }
            java.util.Map<java.lang.String, java.lang.String> map =
                    internalGetBuriedPointMap().getMap();
            if (!map.containsKey(key)) {
                throw new java.lang.IllegalArgumentException();
            }
            return map.get(key);
        }

        public Builder clearBuriedPointMap() {
            bitField0_ = (bitField0_ & ~0x00000080);
            internalGetMutableBuriedPointMap().getMutableMap()
                    .clear();
            return this;
        }

        /**
         * <code>map&lt;string, string&gt; buriedPointMap = 30;</code>
         */
        public Builder removeBuriedPointMap(
                java.lang.String key) {
            if (key == null) {
                throw new NullPointerException("map key");
            }
            internalGetMutableBuriedPointMap().getMutableMap()
                    .remove(key);
            return this;
        }

        /**
         * Use alternate mutation accessors instead.
         */
        @java.lang.Deprecated
        public java.util.Map<java.lang.String, java.lang.String>
        getMutableBuriedPointMap() {
            bitField0_ |= 0x00000080;
            return internalGetMutableBuriedPointMap().getMutableMap();
        }

        /**
         * <code>map&lt;string, string&gt; buriedPointMap = 30;</code>
         */
        public Builder putBuriedPointMap(
                java.lang.String key,
                java.lang.String value) {
            if (key == null) {
                throw new NullPointerException("map key");
            }
            if (value == null) {
                throw new NullPointerException("map value");
            }
            internalGetMutableBuriedPointMap().getMutableMap()
                    .put(key, value);
            bitField0_ |= 0x00000080;
            return this;
        }

        /**
         * <code>map&lt;string, string&gt; buriedPointMap = 30;</code>
         */
        public Builder putAllBuriedPointMap(
                java.util.Map<java.lang.String, java.lang.String> values) {
            internalGetMutableBuriedPointMap().getMutableMap()
                    .putAll(values);
            bitField0_ |= 0x00000080;
            return this;
        }

        @java.lang.Override
        public final Builder setUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:cn.yscme.scrolling.auto.douyin.RoomMessage)
    }

    // @@protoc_insertion_point(class_scope:cn.yscme.scrolling.auto.douyin.RoomMessage)
    private static final cn.yscme.scrolling.auto.douyin.RoomMessage DEFAULT_INSTANCE;

    static {
        DEFAULT_INSTANCE = new cn.yscme.scrolling.auto.douyin.RoomMessage();
    }

    public static cn.yscme.scrolling.auto.douyin.RoomMessage getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RoomMessage>
            PARSER = new com.google.protobuf.AbstractParser<RoomMessage>() {
        @java.lang.Override
        public RoomMessage parsePartialFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            Builder builder = newBuilder();
            try {
                builder.mergeFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(builder.buildPartial());
            } catch (com.google.protobuf.UninitializedMessageException e) {
                throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(e)
                        .setUnfinishedMessage(builder.buildPartial());
            }
            return builder.buildPartial();
        }
    };

    public static com.google.protobuf.Parser<RoomMessage> parser() {
        return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RoomMessage> getParserForType() {
        return PARSER;
    }

    @java.lang.Override
    public cn.yscme.scrolling.auto.douyin.RoomMessage getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }

}

