// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: douyin.proto

// Protobuf Java Version: 3.25.1
package cn.yscme.scrolling.auto.douyin;

/**
 * <pre>
 * from https://github.com/scx567888/live-room-watcher/blob/master/src/main/proto/douyin_hack/webcast/im/RoomRankMessage.proto
 * 直播间排行榜
 * </pre>
 * <p>
 * Protobuf type {@code cn.yscme.scrolling.auto.douyin.RoomRankMessage}
 */
public final class RoomRankMessage extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:cn.yscme.scrolling.auto.douyin.RoomRankMessage)
        RoomRankMessageOrBuilder {
    private static final long serialVersionUID = 0L;

    // Use RoomRankMessage.newBuilder() to construct.
    private RoomRankMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
    }

    private RoomRankMessage() {
        ranksList_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
            UnusedPrivateParameter unused) {
        return new RoomRankMessage();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
        return cn.yscme.scrolling.auto.douyin.Douyin.internal_static_cn_yscme_scrolling_auto_douyin_RoomRankMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
        return cn.yscme.scrolling.auto.douyin.Douyin.internal_static_cn_yscme_scrolling_auto_douyin_RoomRankMessage_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        cn.yscme.scrolling.auto.douyin.RoomRankMessage.class, cn.yscme.scrolling.auto.douyin.RoomRankMessage.Builder.class);
    }

    public interface RoomRankOrBuilder extends
            // @@protoc_insertion_point(interface_extends:cn.yscme.scrolling.auto.douyin.RoomRankMessage.RoomRank)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>.cn.yscme.scrolling.auto.douyin.User user = 1;</code>
         *
         * @return Whether the user field is set.
         */
        boolean hasUser();

        /**
         * <code>.cn.yscme.scrolling.auto.douyin.User user = 1;</code>
         *
         * @return The user.
         */
        cn.yscme.scrolling.auto.douyin.User getUser();

        /**
         * <code>.cn.yscme.scrolling.auto.douyin.User user = 1;</code>
         */
        cn.yscme.scrolling.auto.douyin.UserOrBuilder getUserOrBuilder();

        /**
         * <code>string scoreStr = 2;</code>
         *
         * @return The scoreStr.
         */
        java.lang.String getScoreStr();

        /**
         * <code>string scoreStr = 2;</code>
         *
         * @return The bytes for scoreStr.
         */
        com.google.protobuf.ByteString
        getScoreStrBytes();

        /**
         * <code>bool profileHidden = 3;</code>
         *
         * @return The profileHidden.
         */
        boolean getProfileHidden();
    }

    /**
     * Protobuf type {@code cn.yscme.scrolling.auto.douyin.RoomRankMessage.RoomRank}
     */
    public static final class RoomRank extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:cn.yscme.scrolling.auto.douyin.RoomRankMessage.RoomRank)
            RoomRankOrBuilder {
        private static final long serialVersionUID = 0L;

        // Use RoomRank.newBuilder() to construct.
        private RoomRank(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private RoomRank() {
            scoreStr_ = "";
        }

        @java.lang.Override
        @SuppressWarnings({"unused"})
        protected java.lang.Object newInstance(
                UnusedPrivateParameter unused) {
            return new RoomRank();
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return cn.yscme.scrolling.auto.douyin.Douyin.internal_static_cn_yscme_scrolling_auto_douyin_RoomRankMessage_RoomRank_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return cn.yscme.scrolling.auto.douyin.Douyin.internal_static_cn_yscme_scrolling_auto_douyin_RoomRankMessage_RoomRank_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            cn.yscme.scrolling.auto.douyin.RoomRankMessage.RoomRank.class, cn.yscme.scrolling.auto.douyin.RoomRankMessage.RoomRank.Builder.class);
        }

        private int bitField0_;
        public static final int USER_FIELD_NUMBER = 1;
        private cn.yscme.scrolling.auto.douyin.User user_;

        /**
         * <code>.cn.yscme.scrolling.auto.douyin.User user = 1;</code>
         *
         * @return Whether the user field is set.
         */
        @java.lang.Override
        public boolean hasUser() {
            return ((bitField0_ & 0x00000001) != 0);
        }

        /**
         * <code>.cn.yscme.scrolling.auto.douyin.User user = 1;</code>
         *
         * @return The user.
         */
        @java.lang.Override
        public cn.yscme.scrolling.auto.douyin.User getUser() {
            return user_ == null ? cn.yscme.scrolling.auto.douyin.User.getDefaultInstance() : user_;
        }

        /**
         * <code>.cn.yscme.scrolling.auto.douyin.User user = 1;</code>
         */
        @java.lang.Override
        public cn.yscme.scrolling.auto.douyin.UserOrBuilder getUserOrBuilder() {
            return user_ == null ? cn.yscme.scrolling.auto.douyin.User.getDefaultInstance() : user_;
        }

        public static final int SCORESTR_FIELD_NUMBER = 2;
        @SuppressWarnings("serial")
        private volatile java.lang.Object scoreStr_ = "";

        /**
         * <code>string scoreStr = 2;</code>
         *
         * @return The scoreStr.
         */
        @java.lang.Override
        public java.lang.String getScoreStr() {
            java.lang.Object ref = scoreStr_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                scoreStr_ = s;
                return s;
            }
        }

        /**
         * <code>string scoreStr = 2;</code>
         *
         * @return The bytes for scoreStr.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString
        getScoreStrBytes() {
            java.lang.Object ref = scoreStr_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                scoreStr_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int PROFILEHIDDEN_FIELD_NUMBER = 3;
        private boolean profileHidden_ = false;

        /**
         * <code>bool profileHidden = 3;</code>
         *
         * @return The profileHidden.
         */
        @java.lang.Override
        public boolean getProfileHidden() {
            return profileHidden_;
        }

        private byte memoizedIsInitialized = -1;

        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (((bitField0_ & 0x00000001) != 0)) {
                output.writeMessage(1, getUser());
            }
            if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(scoreStr_)) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 2, scoreStr_);
            }
            if (profileHidden_ != false) {
                output.writeBool(3, profileHidden_);
            }
            getUnknownFields().writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (((bitField0_ & 0x00000001) != 0)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(1, getUser());
            }
            if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(scoreStr_)) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, scoreStr_);
            }
            if (profileHidden_ != false) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBoolSize(3, profileHidden_);
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof cn.yscme.scrolling.auto.douyin.RoomRankMessage.RoomRank)) {
                return super.equals(obj);
            }
            cn.yscme.scrolling.auto.douyin.RoomRankMessage.RoomRank other = (cn.yscme.scrolling.auto.douyin.RoomRankMessage.RoomRank) obj;

            if (hasUser() != other.hasUser()) return false;
            if (hasUser()) {
                if (!getUser()
                        .equals(other.getUser())) return false;
            }
            if (!getScoreStr()
                    .equals(other.getScoreStr())) return false;
            if (getProfileHidden()
                    != other.getProfileHidden()) return false;
            if (!getUnknownFields().equals(other.getUnknownFields())) return false;
            return true;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            if (hasUser()) {
                hash = (37 * hash) + USER_FIELD_NUMBER;
                hash = (53 * hash) + getUser().hashCode();
            }
            hash = (37 * hash) + SCORESTR_FIELD_NUMBER;
            hash = (53 * hash) + getScoreStr().hashCode();
            hash = (37 * hash) + PROFILEHIDDEN_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
                    getProfileHidden());
            hash = (29 * hash) + getUnknownFields().hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static cn.yscme.scrolling.auto.douyin.RoomRankMessage.RoomRank parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static cn.yscme.scrolling.auto.douyin.RoomRankMessage.RoomRank parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static cn.yscme.scrolling.auto.douyin.RoomRankMessage.RoomRank parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static cn.yscme.scrolling.auto.douyin.RoomRankMessage.RoomRank parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static cn.yscme.scrolling.auto.douyin.RoomRankMessage.RoomRank parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static cn.yscme.scrolling.auto.douyin.RoomRankMessage.RoomRank parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static cn.yscme.scrolling.auto.douyin.RoomRankMessage.RoomRank parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static cn.yscme.scrolling.auto.douyin.RoomRankMessage.RoomRank parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static cn.yscme.scrolling.auto.douyin.RoomRankMessage.RoomRank parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static cn.yscme.scrolling.auto.douyin.RoomRankMessage.RoomRank parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static cn.yscme.scrolling.auto.douyin.RoomRankMessage.RoomRank parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static cn.yscme.scrolling.auto.douyin.RoomRankMessage.RoomRank parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(cn.yscme.scrolling.auto.douyin.RoomRankMessage.RoomRank prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code cn.yscme.scrolling.auto.douyin.RoomRankMessage.RoomRank}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:cn.yscme.scrolling.auto.douyin.RoomRankMessage.RoomRank)
                cn.yscme.scrolling.auto.douyin.RoomRankMessage.RoomRankOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return cn.yscme.scrolling.auto.douyin.Douyin.internal_static_cn_yscme_scrolling_auto_douyin_RoomRankMessage_RoomRank_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return cn.yscme.scrolling.auto.douyin.Douyin.internal_static_cn_yscme_scrolling_auto_douyin_RoomRankMessage_RoomRank_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                cn.yscme.scrolling.auto.douyin.RoomRankMessage.RoomRank.class, cn.yscme.scrolling.auto.douyin.RoomRankMessage.RoomRank.Builder.class);
            }

            // Construct using cn.yscme.scrolling.auto.douyin.RoomRankMessage.RoomRank.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                    getUserFieldBuilder();
                }
            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                bitField0_ = 0;
                user_ = null;
                if (userBuilder_ != null) {
                    userBuilder_.dispose();
                    userBuilder_ = null;
                }
                scoreStr_ = "";
                profileHidden_ = false;
                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return cn.yscme.scrolling.auto.douyin.Douyin.internal_static_cn_yscme_scrolling_auto_douyin_RoomRankMessage_RoomRank_descriptor;
            }

            @java.lang.Override
            public cn.yscme.scrolling.auto.douyin.RoomRankMessage.RoomRank getDefaultInstanceForType() {
                return cn.yscme.scrolling.auto.douyin.RoomRankMessage.RoomRank.getDefaultInstance();
            }

            @java.lang.Override
            public cn.yscme.scrolling.auto.douyin.RoomRankMessage.RoomRank build() {
                cn.yscme.scrolling.auto.douyin.RoomRankMessage.RoomRank result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public cn.yscme.scrolling.auto.douyin.RoomRankMessage.RoomRank buildPartial() {
                cn.yscme.scrolling.auto.douyin.RoomRankMessage.RoomRank result = new cn.yscme.scrolling.auto.douyin.RoomRankMessage.RoomRank(this);
                if (bitField0_ != 0) {
                    buildPartial0(result);
                }
                onBuilt();
                return result;
            }

            private void buildPartial0(cn.yscme.scrolling.auto.douyin.RoomRankMessage.RoomRank result) {
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) != 0)) {
                    result.user_ = userBuilder_ == null
                            ? user_
                            : userBuilder_.build();
                    to_bitField0_ |= 0x00000001;
                }
                if (((from_bitField0_ & 0x00000002) != 0)) {
                    result.scoreStr_ = scoreStr_;
                }
                if (((from_bitField0_ & 0x00000004) != 0)) {
                    result.profileHidden_ = profileHidden_;
                }
                result.bitField0_ |= to_bitField0_;
            }

            @java.lang.Override
            public Builder clone() {
                return super.clone();
            }

            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.setField(field, value);
            }

            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }

            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }

            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return super.setRepeatedField(field, index, value);
            }

            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.addRepeatedField(field, value);
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof cn.yscme.scrolling.auto.douyin.RoomRankMessage.RoomRank) {
                    return mergeFrom((cn.yscme.scrolling.auto.douyin.RoomRankMessage.RoomRank) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(cn.yscme.scrolling.auto.douyin.RoomRankMessage.RoomRank other) {
                if (other == cn.yscme.scrolling.auto.douyin.RoomRankMessage.RoomRank.getDefaultInstance()) return this;
                if (other.hasUser()) {
                    mergeUser(other.getUser());
                }
                if (!other.getScoreStr().isEmpty()) {
                    scoreStr_ = other.scoreStr_;
                    bitField0_ |= 0x00000002;
                    onChanged();
                }
                if (other.getProfileHidden() != false) {
                    setProfileHidden(other.getProfileHidden());
                }
                this.mergeUnknownFields(other.getUnknownFields());
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                if (extensionRegistry == null) {
                    throw new java.lang.NullPointerException();
                }
                try {
                    boolean done = false;
                    while (!done) {
                        int tag = input.readTag();
                        switch (tag) {
                            case 0:
                                done = true;
                                break;
                            case 10: {
                                input.readMessage(
                                        getUserFieldBuilder().getBuilder(),
                                        extensionRegistry);
                                bitField0_ |= 0x00000001;
                                break;
                            } // case 10
                            case 18: {
                                scoreStr_ = input.readStringRequireUtf8();
                                bitField0_ |= 0x00000002;
                                break;
                            } // case 18
                            case 24: {
                                profileHidden_ = input.readBool();
                                bitField0_ |= 0x00000004;
                                break;
                            } // case 24
                            default: {
                                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                                    done = true; // was an endgroup tag
                                }
                                break;
                            } // default:
                        } // switch (tag)
                    } // while (!done)
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw e.unwrapIOException();
                } finally {
                    onChanged();
                } // finally
                return this;
            }

            private int bitField0_;

            private cn.yscme.scrolling.auto.douyin.User user_;
            private com.google.protobuf.SingleFieldBuilderV3<
                    cn.yscme.scrolling.auto.douyin.User, cn.yscme.scrolling.auto.douyin.User.Builder, cn.yscme.scrolling.auto.douyin.UserOrBuilder> userBuilder_;

            /**
             * <code>.cn.yscme.scrolling.auto.douyin.User user = 1;</code>
             *
             * @return Whether the user field is set.
             */
            public boolean hasUser() {
                return ((bitField0_ & 0x00000001) != 0);
            }

            /**
             * <code>.cn.yscme.scrolling.auto.douyin.User user = 1;</code>
             *
             * @return The user.
             */
            public cn.yscme.scrolling.auto.douyin.User getUser() {
                if (userBuilder_ == null) {
                    return user_ == null ? cn.yscme.scrolling.auto.douyin.User.getDefaultInstance() : user_;
                } else {
                    return userBuilder_.getMessage();
                }
            }

            /**
             * <code>.cn.yscme.scrolling.auto.douyin.User user = 1;</code>
             */
            public Builder setUser(cn.yscme.scrolling.auto.douyin.User value) {
                if (userBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    user_ = value;
                } else {
                    userBuilder_.setMessage(value);
                }
                bitField0_ |= 0x00000001;
                onChanged();
                return this;
            }

            /**
             * <code>.cn.yscme.scrolling.auto.douyin.User user = 1;</code>
             */
            public Builder setUser(
                    cn.yscme.scrolling.auto.douyin.User.Builder builderForValue) {
                if (userBuilder_ == null) {
                    user_ = builderForValue.build();
                } else {
                    userBuilder_.setMessage(builderForValue.build());
                }
                bitField0_ |= 0x00000001;
                onChanged();
                return this;
            }

            /**
             * <code>.cn.yscme.scrolling.auto.douyin.User user = 1;</code>
             */
            public Builder mergeUser(cn.yscme.scrolling.auto.douyin.User value) {
                if (userBuilder_ == null) {
                    if (((bitField0_ & 0x00000001) != 0) &&
                            user_ != null &&
                            user_ != cn.yscme.scrolling.auto.douyin.User.getDefaultInstance()) {
                        getUserBuilder().mergeFrom(value);
                    } else {
                        user_ = value;
                    }
                } else {
                    userBuilder_.mergeFrom(value);
                }
                if (user_ != null) {
                    bitField0_ |= 0x00000001;
                    onChanged();
                }
                return this;
            }

            /**
             * <code>.cn.yscme.scrolling.auto.douyin.User user = 1;</code>
             */
            public Builder clearUser() {
                bitField0_ = (bitField0_ & ~0x00000001);
                user_ = null;
                if (userBuilder_ != null) {
                    userBuilder_.dispose();
                    userBuilder_ = null;
                }
                onChanged();
                return this;
            }

            /**
             * <code>.cn.yscme.scrolling.auto.douyin.User user = 1;</code>
             */
            public cn.yscme.scrolling.auto.douyin.User.Builder getUserBuilder() {
                bitField0_ |= 0x00000001;
                onChanged();
                return getUserFieldBuilder().getBuilder();
            }

            /**
             * <code>.cn.yscme.scrolling.auto.douyin.User user = 1;</code>
             */
            public cn.yscme.scrolling.auto.douyin.UserOrBuilder getUserOrBuilder() {
                if (userBuilder_ != null) {
                    return userBuilder_.getMessageOrBuilder();
                } else {
                    return user_ == null ?
                            cn.yscme.scrolling.auto.douyin.User.getDefaultInstance() : user_;
                }
            }

            /**
             * <code>.cn.yscme.scrolling.auto.douyin.User user = 1;</code>
             */
            private com.google.protobuf.SingleFieldBuilderV3<
                    cn.yscme.scrolling.auto.douyin.User, cn.yscme.scrolling.auto.douyin.User.Builder, cn.yscme.scrolling.auto.douyin.UserOrBuilder>
            getUserFieldBuilder() {
                if (userBuilder_ == null) {
                    userBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                            cn.yscme.scrolling.auto.douyin.User, cn.yscme.scrolling.auto.douyin.User.Builder, cn.yscme.scrolling.auto.douyin.UserOrBuilder>(
                            getUser(),
                            getParentForChildren(),
                            isClean());
                    user_ = null;
                }
                return userBuilder_;
            }

            private java.lang.Object scoreStr_ = "";

            /**
             * <code>string scoreStr = 2;</code>
             *
             * @return The scoreStr.
             */
            public java.lang.String getScoreStr() {
                java.lang.Object ref = scoreStr_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    scoreStr_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>string scoreStr = 2;</code>
             *
             * @return The bytes for scoreStr.
             */
            public com.google.protobuf.ByteString
            getScoreStrBytes() {
                java.lang.Object ref = scoreStr_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    scoreStr_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string scoreStr = 2;</code>
             *
             * @param value The scoreStr to set.
             * @return This builder for chaining.
             */
            public Builder setScoreStr(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                scoreStr_ = value;
                bitField0_ |= 0x00000002;
                onChanged();
                return this;
            }

            /**
             * <code>string scoreStr = 2;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearScoreStr() {
                scoreStr_ = getDefaultInstance().getScoreStr();
                bitField0_ = (bitField0_ & ~0x00000002);
                onChanged();
                return this;
            }

            /**
             * <code>string scoreStr = 2;</code>
             *
             * @param value The bytes for scoreStr to set.
             * @return This builder for chaining.
             */
            public Builder setScoreStrBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);
                scoreStr_ = value;
                bitField0_ |= 0x00000002;
                onChanged();
                return this;
            }

            private boolean profileHidden_;

            /**
             * <code>bool profileHidden = 3;</code>
             *
             * @return The profileHidden.
             */
            @java.lang.Override
            public boolean getProfileHidden() {
                return profileHidden_;
            }

            /**
             * <code>bool profileHidden = 3;</code>
             *
             * @param value The profileHidden to set.
             * @return This builder for chaining.
             */
            public Builder setProfileHidden(boolean value) {

                profileHidden_ = value;
                bitField0_ |= 0x00000004;
                onChanged();
                return this;
            }

            /**
             * <code>bool profileHidden = 3;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearProfileHidden() {
                bitField0_ = (bitField0_ & ~0x00000004);
                profileHidden_ = false;
                onChanged();
                return this;
            }

            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:cn.yscme.scrolling.auto.douyin.RoomRankMessage.RoomRank)
        }

        // @@protoc_insertion_point(class_scope:cn.yscme.scrolling.auto.douyin.RoomRankMessage.RoomRank)
        private static final cn.yscme.scrolling.auto.douyin.RoomRankMessage.RoomRank DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new cn.yscme.scrolling.auto.douyin.RoomRankMessage.RoomRank();
        }

        public static cn.yscme.scrolling.auto.douyin.RoomRankMessage.RoomRank getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<RoomRank>
                PARSER = new com.google.protobuf.AbstractParser<RoomRank>() {
            @java.lang.Override
            public RoomRank parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                Builder builder = newBuilder();
                try {
                    builder.mergeFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw e.setUnfinishedMessage(builder.buildPartial());
                } catch (com.google.protobuf.UninitializedMessageException e) {
                    throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
                } catch (java.io.IOException e) {
                    throw new com.google.protobuf.InvalidProtocolBufferException(e)
                            .setUnfinishedMessage(builder.buildPartial());
                }
                return builder.buildPartial();
            }
        };

        public static com.google.protobuf.Parser<RoomRank> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<RoomRank> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public cn.yscme.scrolling.auto.douyin.RoomRankMessage.RoomRank getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private int bitField0_;
    public static final int COMMON_FIELD_NUMBER = 1;
    private cn.yscme.scrolling.auto.douyin.Common common_;

    /**
     * <code>.cn.yscme.scrolling.auto.douyin.Common common = 1;</code>
     *
     * @return Whether the common field is set.
     */
    @java.lang.Override
    public boolean hasCommon() {
        return ((bitField0_ & 0x00000001) != 0);
    }

    /**
     * <code>.cn.yscme.scrolling.auto.douyin.Common common = 1;</code>
     *
     * @return The common.
     */
    @java.lang.Override
    public cn.yscme.scrolling.auto.douyin.Common getCommon() {
        return common_ == null ? cn.yscme.scrolling.auto.douyin.Common.getDefaultInstance() : common_;
    }

    /**
     * <code>.cn.yscme.scrolling.auto.douyin.Common common = 1;</code>
     */
    @java.lang.Override
    public cn.yscme.scrolling.auto.douyin.CommonOrBuilder getCommonOrBuilder() {
        return common_ == null ? cn.yscme.scrolling.auto.douyin.Common.getDefaultInstance() : common_;
    }

    public static final int RANKSLIST_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private java.util.List<cn.yscme.scrolling.auto.douyin.RoomRankMessage.RoomRank> ranksList_;

    /**
     * <code>repeated .cn.yscme.scrolling.auto.douyin.RoomRankMessage.RoomRank ranksList = 2;</code>
     */
    @java.lang.Override
    public java.util.List<cn.yscme.scrolling.auto.douyin.RoomRankMessage.RoomRank> getRanksListList() {
        return ranksList_;
    }

    /**
     * <code>repeated .cn.yscme.scrolling.auto.douyin.RoomRankMessage.RoomRank ranksList = 2;</code>
     */
    @java.lang.Override
    public java.util.List<? extends cn.yscme.scrolling.auto.douyin.RoomRankMessage.RoomRankOrBuilder>
    getRanksListOrBuilderList() {
        return ranksList_;
    }

    /**
     * <code>repeated .cn.yscme.scrolling.auto.douyin.RoomRankMessage.RoomRank ranksList = 2;</code>
     */
    @java.lang.Override
    public int getRanksListCount() {
        return ranksList_.size();
    }

    /**
     * <code>repeated .cn.yscme.scrolling.auto.douyin.RoomRankMessage.RoomRank ranksList = 2;</code>
     */
    @java.lang.Override
    public cn.yscme.scrolling.auto.douyin.RoomRankMessage.RoomRank getRanksList(int index) {
        return ranksList_.get(index);
    }

    /**
     * <code>repeated .cn.yscme.scrolling.auto.douyin.RoomRankMessage.RoomRank ranksList = 2;</code>
     */
    @java.lang.Override
    public cn.yscme.scrolling.auto.douyin.RoomRankMessage.RoomRankOrBuilder getRanksListOrBuilder(
            int index) {
        return ranksList_.get(index);
    }

    private byte memoizedIsInitialized = -1;

    @java.lang.Override
    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
        if (((bitField0_ & 0x00000001) != 0)) {
            output.writeMessage(1, getCommon());
        }
        for (int i = 0; i < ranksList_.size(); i++) {
            output.writeMessage(2, ranksList_.get(i));
        }
        getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) != 0)) {
            size += com.google.protobuf.CodedOutputStream
                    .computeMessageSize(1, getCommon());
        }
        for (int i = 0; i < ranksList_.size(); i++) {
            size += com.google.protobuf.CodedOutputStream
                    .computeMessageSize(2, ranksList_.get(i));
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof cn.yscme.scrolling.auto.douyin.RoomRankMessage)) {
            return super.equals(obj);
        }
        cn.yscme.scrolling.auto.douyin.RoomRankMessage other = (cn.yscme.scrolling.auto.douyin.RoomRankMessage) obj;

        if (hasCommon() != other.hasCommon()) return false;
        if (hasCommon()) {
            if (!getCommon()
                    .equals(other.getCommon())) return false;
        }
        if (!getRanksListList()
                .equals(other.getRanksListList())) return false;
        if (!getUnknownFields().equals(other.getUnknownFields())) return false;
        return true;
    }

    @java.lang.Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (hasCommon()) {
            hash = (37 * hash) + COMMON_FIELD_NUMBER;
            hash = (53 * hash) + getCommon().hashCode();
        }
        if (getRanksListCount() > 0) {
            hash = (37 * hash) + RANKSLIST_FIELD_NUMBER;
            hash = (53 * hash) + getRanksListList().hashCode();
        }
        hash = (29 * hash) + getUnknownFields().hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    public static cn.yscme.scrolling.auto.douyin.RoomRankMessage parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static cn.yscme.scrolling.auto.douyin.RoomRankMessage parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static cn.yscme.scrolling.auto.douyin.RoomRankMessage parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static cn.yscme.scrolling.auto.douyin.RoomRankMessage parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static cn.yscme.scrolling.auto.douyin.RoomRankMessage parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static cn.yscme.scrolling.auto.douyin.RoomRankMessage parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static cn.yscme.scrolling.auto.douyin.RoomRankMessage parseFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static cn.yscme.scrolling.auto.douyin.RoomRankMessage parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static cn.yscme.scrolling.auto.douyin.RoomRankMessage parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input);
    }

    public static cn.yscme.scrolling.auto.douyin.RoomRankMessage parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static cn.yscme.scrolling.auto.douyin.RoomRankMessage parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static cn.yscme.scrolling.auto.douyin.RoomRankMessage parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() {
        return newBuilder();
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(cn.yscme.scrolling.auto.douyin.RoomRankMessage prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @java.lang.Override
    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
                ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    /**
     * <pre>
     * from https://github.com/scx567888/live-room-watcher/blob/master/src/main/proto/douyin_hack/webcast/im/RoomRankMessage.proto
     * 直播间排行榜
     * </pre>
     * <p>
     * Protobuf type {@code cn.yscme.scrolling.auto.douyin.RoomRankMessage}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:cn.yscme.scrolling.auto.douyin.RoomRankMessage)
            cn.yscme.scrolling.auto.douyin.RoomRankMessageOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return cn.yscme.scrolling.auto.douyin.Douyin.internal_static_cn_yscme_scrolling_auto_douyin_RoomRankMessage_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return cn.yscme.scrolling.auto.douyin.Douyin.internal_static_cn_yscme_scrolling_auto_douyin_RoomRankMessage_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            cn.yscme.scrolling.auto.douyin.RoomRankMessage.class, cn.yscme.scrolling.auto.douyin.RoomRankMessage.Builder.class);
        }

        // Construct using cn.yscme.scrolling.auto.douyin.RoomRankMessage.newBuilder()
        private Builder() {
            maybeForceBuilderInitialization();
        }

        private Builder(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
        }

        private void maybeForceBuilderInitialization() {
            if (com.google.protobuf.GeneratedMessageV3
                    .alwaysUseFieldBuilders) {
                getCommonFieldBuilder();
                getRanksListFieldBuilder();
            }
        }

        @java.lang.Override
        public Builder clear() {
            super.clear();
            bitField0_ = 0;
            common_ = null;
            if (commonBuilder_ != null) {
                commonBuilder_.dispose();
                commonBuilder_ = null;
            }
            if (ranksListBuilder_ == null) {
                ranksList_ = java.util.Collections.emptyList();
            } else {
                ranksList_ = null;
                ranksListBuilder_.clear();
            }
            bitField0_ = (bitField0_ & ~0x00000002);
            return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
            return cn.yscme.scrolling.auto.douyin.Douyin.internal_static_cn_yscme_scrolling_auto_douyin_RoomRankMessage_descriptor;
        }

        @java.lang.Override
        public cn.yscme.scrolling.auto.douyin.RoomRankMessage getDefaultInstanceForType() {
            return cn.yscme.scrolling.auto.douyin.RoomRankMessage.getDefaultInstance();
        }

        @java.lang.Override
        public cn.yscme.scrolling.auto.douyin.RoomRankMessage build() {
            cn.yscme.scrolling.auto.douyin.RoomRankMessage result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        @java.lang.Override
        public cn.yscme.scrolling.auto.douyin.RoomRankMessage buildPartial() {
            cn.yscme.scrolling.auto.douyin.RoomRankMessage result = new cn.yscme.scrolling.auto.douyin.RoomRankMessage(this);
            buildPartialRepeatedFields(result);
            if (bitField0_ != 0) {
                buildPartial0(result);
            }
            onBuilt();
            return result;
        }

        private void buildPartialRepeatedFields(cn.yscme.scrolling.auto.douyin.RoomRankMessage result) {
            if (ranksListBuilder_ == null) {
                if (((bitField0_ & 0x00000002) != 0)) {
                    ranksList_ = java.util.Collections.unmodifiableList(ranksList_);
                    bitField0_ = (bitField0_ & ~0x00000002);
                }
                result.ranksList_ = ranksList_;
            } else {
                result.ranksList_ = ranksListBuilder_.build();
            }
        }

        private void buildPartial0(cn.yscme.scrolling.auto.douyin.RoomRankMessage result) {
            int from_bitField0_ = bitField0_;
            int to_bitField0_ = 0;
            if (((from_bitField0_ & 0x00000001) != 0)) {
                result.common_ = commonBuilder_ == null
                        ? common_
                        : commonBuilder_.build();
                to_bitField0_ |= 0x00000001;
            }
            result.bitField0_ |= to_bitField0_;
        }

        @java.lang.Override
        public Builder clone() {
            return super.clone();
        }

        @java.lang.Override
        public Builder setField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                java.lang.Object value) {
            return super.setField(field, value);
        }

        @java.lang.Override
        public Builder clearField(
                com.google.protobuf.Descriptors.FieldDescriptor field) {
            return super.clearField(field);
        }

        @java.lang.Override
        public Builder clearOneof(
                com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return super.clearOneof(oneof);
        }

        @java.lang.Override
        public Builder setRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                int index, java.lang.Object value) {
            return super.setRepeatedField(field, index, value);
        }

        @java.lang.Override
        public Builder addRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                java.lang.Object value) {
            return super.addRepeatedField(field, value);
        }

        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof cn.yscme.scrolling.auto.douyin.RoomRankMessage) {
                return mergeFrom((cn.yscme.scrolling.auto.douyin.RoomRankMessage) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(cn.yscme.scrolling.auto.douyin.RoomRankMessage other) {
            if (other == cn.yscme.scrolling.auto.douyin.RoomRankMessage.getDefaultInstance()) return this;
            if (other.hasCommon()) {
                mergeCommon(other.getCommon());
            }
            if (ranksListBuilder_ == null) {
                if (!other.ranksList_.isEmpty()) {
                    if (ranksList_.isEmpty()) {
                        ranksList_ = other.ranksList_;
                        bitField0_ = (bitField0_ & ~0x00000002);
                    } else {
                        ensureRanksListIsMutable();
                        ranksList_.addAll(other.ranksList_);
                    }
                    onChanged();
                }
            } else {
                if (!other.ranksList_.isEmpty()) {
                    if (ranksListBuilder_.isEmpty()) {
                        ranksListBuilder_.dispose();
                        ranksListBuilder_ = null;
                        ranksList_ = other.ranksList_;
                        bitField0_ = (bitField0_ & ~0x00000002);
                        ranksListBuilder_ =
                                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                                        getRanksListFieldBuilder() : null;
                    } else {
                        ranksListBuilder_.addAllMessages(other.ranksList_);
                    }
                }
            }
            this.mergeUnknownFields(other.getUnknownFields());
            onChanged();
            return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
            return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 10: {
                            input.readMessage(
                                    getCommonFieldBuilder().getBuilder(),
                                    extensionRegistry);
                            bitField0_ |= 0x00000001;
                            break;
                        } // case 10
                        case 18: {
                            cn.yscme.scrolling.auto.douyin.RoomRankMessage.RoomRank m =
                                    input.readMessage(
                                            cn.yscme.scrolling.auto.douyin.RoomRankMessage.RoomRank.parser(),
                                            extensionRegistry);
                            if (ranksListBuilder_ == null) {
                                ensureRanksListIsMutable();
                                ranksList_.add(m);
                            } else {
                                ranksListBuilder_.addMessage(m);
                            }
                            break;
                        } // case 18
                        default: {
                            if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                                done = true; // was an endgroup tag
                            }
                            break;
                        } // default:
                    } // switch (tag)
                } // while (!done)
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.unwrapIOException();
            } finally {
                onChanged();
            } // finally
            return this;
        }

        private int bitField0_;

        private cn.yscme.scrolling.auto.douyin.Common common_;
        private com.google.protobuf.SingleFieldBuilderV3<
                cn.yscme.scrolling.auto.douyin.Common, cn.yscme.scrolling.auto.douyin.Common.Builder, cn.yscme.scrolling.auto.douyin.CommonOrBuilder> commonBuilder_;

        /**
         * <code>.cn.yscme.scrolling.auto.douyin.Common common = 1;</code>
         *
         * @return Whether the common field is set.
         */
        public boolean hasCommon() {
            return ((bitField0_ & 0x00000001) != 0);
        }

        /**
         * <code>.cn.yscme.scrolling.auto.douyin.Common common = 1;</code>
         *
         * @return The common.
         */
        public cn.yscme.scrolling.auto.douyin.Common getCommon() {
            if (commonBuilder_ == null) {
                return common_ == null ? cn.yscme.scrolling.auto.douyin.Common.getDefaultInstance() : common_;
            } else {
                return commonBuilder_.getMessage();
            }
        }

        /**
         * <code>.cn.yscme.scrolling.auto.douyin.Common common = 1;</code>
         */
        public Builder setCommon(cn.yscme.scrolling.auto.douyin.Common value) {
            if (commonBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                common_ = value;
            } else {
                commonBuilder_.setMessage(value);
            }
            bitField0_ |= 0x00000001;
            onChanged();
            return this;
        }

        /**
         * <code>.cn.yscme.scrolling.auto.douyin.Common common = 1;</code>
         */
        public Builder setCommon(
                cn.yscme.scrolling.auto.douyin.Common.Builder builderForValue) {
            if (commonBuilder_ == null) {
                common_ = builderForValue.build();
            } else {
                commonBuilder_.setMessage(builderForValue.build());
            }
            bitField0_ |= 0x00000001;
            onChanged();
            return this;
        }

        /**
         * <code>.cn.yscme.scrolling.auto.douyin.Common common = 1;</code>
         */
        public Builder mergeCommon(cn.yscme.scrolling.auto.douyin.Common value) {
            if (commonBuilder_ == null) {
                if (((bitField0_ & 0x00000001) != 0) &&
                        common_ != null &&
                        common_ != cn.yscme.scrolling.auto.douyin.Common.getDefaultInstance()) {
                    getCommonBuilder().mergeFrom(value);
                } else {
                    common_ = value;
                }
            } else {
                commonBuilder_.mergeFrom(value);
            }
            if (common_ != null) {
                bitField0_ |= 0x00000001;
                onChanged();
            }
            return this;
        }

        /**
         * <code>.cn.yscme.scrolling.auto.douyin.Common common = 1;</code>
         */
        public Builder clearCommon() {
            bitField0_ = (bitField0_ & ~0x00000001);
            common_ = null;
            if (commonBuilder_ != null) {
                commonBuilder_.dispose();
                commonBuilder_ = null;
            }
            onChanged();
            return this;
        }

        /**
         * <code>.cn.yscme.scrolling.auto.douyin.Common common = 1;</code>
         */
        public cn.yscme.scrolling.auto.douyin.Common.Builder getCommonBuilder() {
            bitField0_ |= 0x00000001;
            onChanged();
            return getCommonFieldBuilder().getBuilder();
        }

        /**
         * <code>.cn.yscme.scrolling.auto.douyin.Common common = 1;</code>
         */
        public cn.yscme.scrolling.auto.douyin.CommonOrBuilder getCommonOrBuilder() {
            if (commonBuilder_ != null) {
                return commonBuilder_.getMessageOrBuilder();
            } else {
                return common_ == null ?
                        cn.yscme.scrolling.auto.douyin.Common.getDefaultInstance() : common_;
            }
        }

        /**
         * <code>.cn.yscme.scrolling.auto.douyin.Common common = 1;</code>
         */
        private com.google.protobuf.SingleFieldBuilderV3<
                cn.yscme.scrolling.auto.douyin.Common, cn.yscme.scrolling.auto.douyin.Common.Builder, cn.yscme.scrolling.auto.douyin.CommonOrBuilder>
        getCommonFieldBuilder() {
            if (commonBuilder_ == null) {
                commonBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                        cn.yscme.scrolling.auto.douyin.Common, cn.yscme.scrolling.auto.douyin.Common.Builder, cn.yscme.scrolling.auto.douyin.CommonOrBuilder>(
                        getCommon(),
                        getParentForChildren(),
                        isClean());
                common_ = null;
            }
            return commonBuilder_;
        }

        private java.util.List<cn.yscme.scrolling.auto.douyin.RoomRankMessage.RoomRank> ranksList_ =
                java.util.Collections.emptyList();

        private void ensureRanksListIsMutable() {
            if (!((bitField0_ & 0x00000002) != 0)) {
                ranksList_ = new java.util.ArrayList<cn.yscme.scrolling.auto.douyin.RoomRankMessage.RoomRank>(ranksList_);
                bitField0_ |= 0x00000002;
            }
        }

        private com.google.protobuf.RepeatedFieldBuilderV3<
                cn.yscme.scrolling.auto.douyin.RoomRankMessage.RoomRank, cn.yscme.scrolling.auto.douyin.RoomRankMessage.RoomRank.Builder, cn.yscme.scrolling.auto.douyin.RoomRankMessage.RoomRankOrBuilder> ranksListBuilder_;

        /**
         * <code>repeated .cn.yscme.scrolling.auto.douyin.RoomRankMessage.RoomRank ranksList = 2;</code>
         */
        public java.util.List<cn.yscme.scrolling.auto.douyin.RoomRankMessage.RoomRank> getRanksListList() {
            if (ranksListBuilder_ == null) {
                return java.util.Collections.unmodifiableList(ranksList_);
            } else {
                return ranksListBuilder_.getMessageList();
            }
        }

        /**
         * <code>repeated .cn.yscme.scrolling.auto.douyin.RoomRankMessage.RoomRank ranksList = 2;</code>
         */
        public int getRanksListCount() {
            if (ranksListBuilder_ == null) {
                return ranksList_.size();
            } else {
                return ranksListBuilder_.getCount();
            }
        }

        /**
         * <code>repeated .cn.yscme.scrolling.auto.douyin.RoomRankMessage.RoomRank ranksList = 2;</code>
         */
        public cn.yscme.scrolling.auto.douyin.RoomRankMessage.RoomRank getRanksList(int index) {
            if (ranksListBuilder_ == null) {
                return ranksList_.get(index);
            } else {
                return ranksListBuilder_.getMessage(index);
            }
        }

        /**
         * <code>repeated .cn.yscme.scrolling.auto.douyin.RoomRankMessage.RoomRank ranksList = 2;</code>
         */
        public Builder setRanksList(
                int index, cn.yscme.scrolling.auto.douyin.RoomRankMessage.RoomRank value) {
            if (ranksListBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureRanksListIsMutable();
                ranksList_.set(index, value);
                onChanged();
            } else {
                ranksListBuilder_.setMessage(index, value);
            }
            return this;
        }

        /**
         * <code>repeated .cn.yscme.scrolling.auto.douyin.RoomRankMessage.RoomRank ranksList = 2;</code>
         */
        public Builder setRanksList(
                int index, cn.yscme.scrolling.auto.douyin.RoomRankMessage.RoomRank.Builder builderForValue) {
            if (ranksListBuilder_ == null) {
                ensureRanksListIsMutable();
                ranksList_.set(index, builderForValue.build());
                onChanged();
            } else {
                ranksListBuilder_.setMessage(index, builderForValue.build());
            }
            return this;
        }

        /**
         * <code>repeated .cn.yscme.scrolling.auto.douyin.RoomRankMessage.RoomRank ranksList = 2;</code>
         */
        public Builder addRanksList(cn.yscme.scrolling.auto.douyin.RoomRankMessage.RoomRank value) {
            if (ranksListBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureRanksListIsMutable();
                ranksList_.add(value);
                onChanged();
            } else {
                ranksListBuilder_.addMessage(value);
            }
            return this;
        }

        /**
         * <code>repeated .cn.yscme.scrolling.auto.douyin.RoomRankMessage.RoomRank ranksList = 2;</code>
         */
        public Builder addRanksList(
                int index, cn.yscme.scrolling.auto.douyin.RoomRankMessage.RoomRank value) {
            if (ranksListBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureRanksListIsMutable();
                ranksList_.add(index, value);
                onChanged();
            } else {
                ranksListBuilder_.addMessage(index, value);
            }
            return this;
        }

        /**
         * <code>repeated .cn.yscme.scrolling.auto.douyin.RoomRankMessage.RoomRank ranksList = 2;</code>
         */
        public Builder addRanksList(
                cn.yscme.scrolling.auto.douyin.RoomRankMessage.RoomRank.Builder builderForValue) {
            if (ranksListBuilder_ == null) {
                ensureRanksListIsMutable();
                ranksList_.add(builderForValue.build());
                onChanged();
            } else {
                ranksListBuilder_.addMessage(builderForValue.build());
            }
            return this;
        }

        /**
         * <code>repeated .cn.yscme.scrolling.auto.douyin.RoomRankMessage.RoomRank ranksList = 2;</code>
         */
        public Builder addRanksList(
                int index, cn.yscme.scrolling.auto.douyin.RoomRankMessage.RoomRank.Builder builderForValue) {
            if (ranksListBuilder_ == null) {
                ensureRanksListIsMutable();
                ranksList_.add(index, builderForValue.build());
                onChanged();
            } else {
                ranksListBuilder_.addMessage(index, builderForValue.build());
            }
            return this;
        }

        /**
         * <code>repeated .cn.yscme.scrolling.auto.douyin.RoomRankMessage.RoomRank ranksList = 2;</code>
         */
        public Builder addAllRanksList(
                java.lang.Iterable<? extends cn.yscme.scrolling.auto.douyin.RoomRankMessage.RoomRank> values) {
            if (ranksListBuilder_ == null) {
                ensureRanksListIsMutable();
                com.google.protobuf.AbstractMessageLite.Builder.addAll(
                        values, ranksList_);
                onChanged();
            } else {
                ranksListBuilder_.addAllMessages(values);
            }
            return this;
        }

        /**
         * <code>repeated .cn.yscme.scrolling.auto.douyin.RoomRankMessage.RoomRank ranksList = 2;</code>
         */
        public Builder clearRanksList() {
            if (ranksListBuilder_ == null) {
                ranksList_ = java.util.Collections.emptyList();
                bitField0_ = (bitField0_ & ~0x00000002);
                onChanged();
            } else {
                ranksListBuilder_.clear();
            }
            return this;
        }

        /**
         * <code>repeated .cn.yscme.scrolling.auto.douyin.RoomRankMessage.RoomRank ranksList = 2;</code>
         */
        public Builder removeRanksList(int index) {
            if (ranksListBuilder_ == null) {
                ensureRanksListIsMutable();
                ranksList_.remove(index);
                onChanged();
            } else {
                ranksListBuilder_.remove(index);
            }
            return this;
        }

        /**
         * <code>repeated .cn.yscme.scrolling.auto.douyin.RoomRankMessage.RoomRank ranksList = 2;</code>
         */
        public cn.yscme.scrolling.auto.douyin.RoomRankMessage.RoomRank.Builder getRanksListBuilder(
                int index) {
            return getRanksListFieldBuilder().getBuilder(index);
        }

        /**
         * <code>repeated .cn.yscme.scrolling.auto.douyin.RoomRankMessage.RoomRank ranksList = 2;</code>
         */
        public cn.yscme.scrolling.auto.douyin.RoomRankMessage.RoomRankOrBuilder getRanksListOrBuilder(
                int index) {
            if (ranksListBuilder_ == null) {
                return ranksList_.get(index);
            } else {
                return ranksListBuilder_.getMessageOrBuilder(index);
            }
        }

        /**
         * <code>repeated .cn.yscme.scrolling.auto.douyin.RoomRankMessage.RoomRank ranksList = 2;</code>
         */
        public java.util.List<? extends cn.yscme.scrolling.auto.douyin.RoomRankMessage.RoomRankOrBuilder>
        getRanksListOrBuilderList() {
            if (ranksListBuilder_ != null) {
                return ranksListBuilder_.getMessageOrBuilderList();
            } else {
                return java.util.Collections.unmodifiableList(ranksList_);
            }
        }

        /**
         * <code>repeated .cn.yscme.scrolling.auto.douyin.RoomRankMessage.RoomRank ranksList = 2;</code>
         */
        public cn.yscme.scrolling.auto.douyin.RoomRankMessage.RoomRank.Builder addRanksListBuilder() {
            return getRanksListFieldBuilder().addBuilder(
                    cn.yscme.scrolling.auto.douyin.RoomRankMessage.RoomRank.getDefaultInstance());
        }

        /**
         * <code>repeated .cn.yscme.scrolling.auto.douyin.RoomRankMessage.RoomRank ranksList = 2;</code>
         */
        public cn.yscme.scrolling.auto.douyin.RoomRankMessage.RoomRank.Builder addRanksListBuilder(
                int index) {
            return getRanksListFieldBuilder().addBuilder(
                    index, cn.yscme.scrolling.auto.douyin.RoomRankMessage.RoomRank.getDefaultInstance());
        }

        /**
         * <code>repeated .cn.yscme.scrolling.auto.douyin.RoomRankMessage.RoomRank ranksList = 2;</code>
         */
        public java.util.List<cn.yscme.scrolling.auto.douyin.RoomRankMessage.RoomRank.Builder>
        getRanksListBuilderList() {
            return getRanksListFieldBuilder().getBuilderList();
        }

        private com.google.protobuf.RepeatedFieldBuilderV3<
                cn.yscme.scrolling.auto.douyin.RoomRankMessage.RoomRank, cn.yscme.scrolling.auto.douyin.RoomRankMessage.RoomRank.Builder, cn.yscme.scrolling.auto.douyin.RoomRankMessage.RoomRankOrBuilder>
        getRanksListFieldBuilder() {
            if (ranksListBuilder_ == null) {
                ranksListBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
                        cn.yscme.scrolling.auto.douyin.RoomRankMessage.RoomRank, cn.yscme.scrolling.auto.douyin.RoomRankMessage.RoomRank.Builder, cn.yscme.scrolling.auto.douyin.RoomRankMessage.RoomRankOrBuilder>(
                        ranksList_,
                        ((bitField0_ & 0x00000002) != 0),
                        getParentForChildren(),
                        isClean());
                ranksList_ = null;
            }
            return ranksListBuilder_;
        }

        @java.lang.Override
        public final Builder setUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:cn.yscme.scrolling.auto.douyin.RoomRankMessage)
    }

    // @@protoc_insertion_point(class_scope:cn.yscme.scrolling.auto.douyin.RoomRankMessage)
    private static final cn.yscme.scrolling.auto.douyin.RoomRankMessage DEFAULT_INSTANCE;

    static {
        DEFAULT_INSTANCE = new cn.yscme.scrolling.auto.douyin.RoomRankMessage();
    }

    public static cn.yscme.scrolling.auto.douyin.RoomRankMessage getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RoomRankMessage>
            PARSER = new com.google.protobuf.AbstractParser<RoomRankMessage>() {
        @java.lang.Override
        public RoomRankMessage parsePartialFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            Builder builder = newBuilder();
            try {
                builder.mergeFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(builder.buildPartial());
            } catch (com.google.protobuf.UninitializedMessageException e) {
                throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(e)
                        .setUnfinishedMessage(builder.buildPartial());
            }
            return builder.buildPartial();
        }
    };

    public static com.google.protobuf.Parser<RoomRankMessage> parser() {
        return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RoomRankMessage> getParserForType() {
        return PARSER;
    }

    @java.lang.Override
    public cn.yscme.scrolling.auto.douyin.RoomRankMessage getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }

}

