// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: douyin.proto

// Protobuf Java Version: 3.25.1
package cn.yscme.scrolling.auto.douyin;

/**
 * Protobuf type {@code cn.yscme.scrolling.auto.douyin.SocialMessage}
 */
public final class SocialMessage extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:cn.yscme.scrolling.auto.douyin.SocialMessage)
        SocialMessageOrBuilder {
    private static final long serialVersionUID = 0L;

    // Use SocialMessage.newBuilder() to construct.
    private SocialMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
    }

    private SocialMessage() {
        shareTarget_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
            UnusedPrivateParameter unused) {
        return new SocialMessage();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
        return cn.yscme.scrolling.auto.douyin.Douyin.internal_static_cn_yscme_scrolling_auto_douyin_SocialMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
        return cn.yscme.scrolling.auto.douyin.Douyin.internal_static_cn_yscme_scrolling_auto_douyin_SocialMessage_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        cn.yscme.scrolling.auto.douyin.SocialMessage.class, cn.yscme.scrolling.auto.douyin.SocialMessage.Builder.class);
    }

    private int bitField0_;
    public static final int COMMON_FIELD_NUMBER = 1;
    private cn.yscme.scrolling.auto.douyin.Common common_;

    /**
     * <code>.cn.yscme.scrolling.auto.douyin.Common common = 1;</code>
     *
     * @return Whether the common field is set.
     */
    @java.lang.Override
    public boolean hasCommon() {
        return ((bitField0_ & 0x00000001) != 0);
    }

    /**
     * <code>.cn.yscme.scrolling.auto.douyin.Common common = 1;</code>
     *
     * @return The common.
     */
    @java.lang.Override
    public cn.yscme.scrolling.auto.douyin.Common getCommon() {
        return common_ == null ? cn.yscme.scrolling.auto.douyin.Common.getDefaultInstance() : common_;
    }

    /**
     * <code>.cn.yscme.scrolling.auto.douyin.Common common = 1;</code>
     */
    @java.lang.Override
    public cn.yscme.scrolling.auto.douyin.CommonOrBuilder getCommonOrBuilder() {
        return common_ == null ? cn.yscme.scrolling.auto.douyin.Common.getDefaultInstance() : common_;
    }

    public static final int USER_FIELD_NUMBER = 2;
    private cn.yscme.scrolling.auto.douyin.User user_;

    /**
     * <code>.cn.yscme.scrolling.auto.douyin.User user = 2;</code>
     *
     * @return Whether the user field is set.
     */
    @java.lang.Override
    public boolean hasUser() {
        return ((bitField0_ & 0x00000002) != 0);
    }

    /**
     * <code>.cn.yscme.scrolling.auto.douyin.User user = 2;</code>
     *
     * @return The user.
     */
    @java.lang.Override
    public cn.yscme.scrolling.auto.douyin.User getUser() {
        return user_ == null ? cn.yscme.scrolling.auto.douyin.User.getDefaultInstance() : user_;
    }

    /**
     * <code>.cn.yscme.scrolling.auto.douyin.User user = 2;</code>
     */
    @java.lang.Override
    public cn.yscme.scrolling.auto.douyin.UserOrBuilder getUserOrBuilder() {
        return user_ == null ? cn.yscme.scrolling.auto.douyin.User.getDefaultInstance() : user_;
    }

    public static final int SHARETYPE_FIELD_NUMBER = 3;
    private long shareType_ = 0L;

    /**
     * <code>uint64 shareType = 3;</code>
     *
     * @return The shareType.
     */
    @java.lang.Override
    public long getShareType() {
        return shareType_;
    }

    public static final int ACTION_FIELD_NUMBER = 4;
    private long action_ = 0L;

    /**
     * <code>uint64 action = 4;</code>
     *
     * @return The action.
     */
    @java.lang.Override
    public long getAction() {
        return action_;
    }

    public static final int SHARETARGET_FIELD_NUMBER = 5;
    @SuppressWarnings("serial")
    private volatile java.lang.Object shareTarget_ = "";

    /**
     * <code>string shareTarget = 5;</code>
     *
     * @return The shareTarget.
     */
    @java.lang.Override
    public java.lang.String getShareTarget() {
        java.lang.Object ref = shareTarget_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            shareTarget_ = s;
            return s;
        }
    }

    /**
     * <code>string shareTarget = 5;</code>
     *
     * @return The bytes for shareTarget.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
    getShareTargetBytes() {
        java.lang.Object ref = shareTarget_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
            shareTarget_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public static final int FOLLOWCOUNT_FIELD_NUMBER = 6;
    private long followCount_ = 0L;

    /**
     * <code>uint64 followCount = 6;</code>
     *
     * @return The followCount.
     */
    @java.lang.Override
    public long getFollowCount() {
        return followCount_;
    }

    public static final int PUBLICAREACOMMON_FIELD_NUMBER = 7;
    private cn.yscme.scrolling.auto.douyin.PublicAreaCommon publicAreaCommon_;

    /**
     * <code>.cn.yscme.scrolling.auto.douyin.PublicAreaCommon publicAreaCommon = 7;</code>
     *
     * @return Whether the publicAreaCommon field is set.
     */
    @java.lang.Override
    public boolean hasPublicAreaCommon() {
        return ((bitField0_ & 0x00000004) != 0);
    }

    /**
     * <code>.cn.yscme.scrolling.auto.douyin.PublicAreaCommon publicAreaCommon = 7;</code>
     *
     * @return The publicAreaCommon.
     */
    @java.lang.Override
    public cn.yscme.scrolling.auto.douyin.PublicAreaCommon getPublicAreaCommon() {
        return publicAreaCommon_ == null ? cn.yscme.scrolling.auto.douyin.PublicAreaCommon.getDefaultInstance() : publicAreaCommon_;
    }

    /**
     * <code>.cn.yscme.scrolling.auto.douyin.PublicAreaCommon publicAreaCommon = 7;</code>
     */
    @java.lang.Override
    public cn.yscme.scrolling.auto.douyin.PublicAreaCommonOrBuilder getPublicAreaCommonOrBuilder() {
        return publicAreaCommon_ == null ? cn.yscme.scrolling.auto.douyin.PublicAreaCommon.getDefaultInstance() : publicAreaCommon_;
    }

    private byte memoizedIsInitialized = -1;

    @java.lang.Override
    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
        if (((bitField0_ & 0x00000001) != 0)) {
            output.writeMessage(1, getCommon());
        }
        if (((bitField0_ & 0x00000002) != 0)) {
            output.writeMessage(2, getUser());
        }
        if (shareType_ != 0L) {
            output.writeUInt64(3, shareType_);
        }
        if (action_ != 0L) {
            output.writeUInt64(4, action_);
        }
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(shareTarget_)) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 5, shareTarget_);
        }
        if (followCount_ != 0L) {
            output.writeUInt64(6, followCount_);
        }
        if (((bitField0_ & 0x00000004) != 0)) {
            output.writeMessage(7, getPublicAreaCommon());
        }
        getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) != 0)) {
            size += com.google.protobuf.CodedOutputStream
                    .computeMessageSize(1, getCommon());
        }
        if (((bitField0_ & 0x00000002) != 0)) {
            size += com.google.protobuf.CodedOutputStream
                    .computeMessageSize(2, getUser());
        }
        if (shareType_ != 0L) {
            size += com.google.protobuf.CodedOutputStream
                    .computeUInt64Size(3, shareType_);
        }
        if (action_ != 0L) {
            size += com.google.protobuf.CodedOutputStream
                    .computeUInt64Size(4, action_);
        }
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(shareTarget_)) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, shareTarget_);
        }
        if (followCount_ != 0L) {
            size += com.google.protobuf.CodedOutputStream
                    .computeUInt64Size(6, followCount_);
        }
        if (((bitField0_ & 0x00000004) != 0)) {
            size += com.google.protobuf.CodedOutputStream
                    .computeMessageSize(7, getPublicAreaCommon());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof cn.yscme.scrolling.auto.douyin.SocialMessage)) {
            return super.equals(obj);
        }
        cn.yscme.scrolling.auto.douyin.SocialMessage other = (cn.yscme.scrolling.auto.douyin.SocialMessage) obj;

        if (hasCommon() != other.hasCommon()) return false;
        if (hasCommon()) {
            if (!getCommon()
                    .equals(other.getCommon())) return false;
        }
        if (hasUser() != other.hasUser()) return false;
        if (hasUser()) {
            if (!getUser()
                    .equals(other.getUser())) return false;
        }
        if (getShareType()
                != other.getShareType()) return false;
        if (getAction()
                != other.getAction()) return false;
        if (!getShareTarget()
                .equals(other.getShareTarget())) return false;
        if (getFollowCount()
                != other.getFollowCount()) return false;
        if (hasPublicAreaCommon() != other.hasPublicAreaCommon()) return false;
        if (hasPublicAreaCommon()) {
            if (!getPublicAreaCommon()
                    .equals(other.getPublicAreaCommon())) return false;
        }
        if (!getUnknownFields().equals(other.getUnknownFields())) return false;
        return true;
    }

    @java.lang.Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (hasCommon()) {
            hash = (37 * hash) + COMMON_FIELD_NUMBER;
            hash = (53 * hash) + getCommon().hashCode();
        }
        if (hasUser()) {
            hash = (37 * hash) + USER_FIELD_NUMBER;
            hash = (53 * hash) + getUser().hashCode();
        }
        hash = (37 * hash) + SHARETYPE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                getShareType());
        hash = (37 * hash) + ACTION_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                getAction());
        hash = (37 * hash) + SHARETARGET_FIELD_NUMBER;
        hash = (53 * hash) + getShareTarget().hashCode();
        hash = (37 * hash) + FOLLOWCOUNT_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                getFollowCount());
        if (hasPublicAreaCommon()) {
            hash = (37 * hash) + PUBLICAREACOMMON_FIELD_NUMBER;
            hash = (53 * hash) + getPublicAreaCommon().hashCode();
        }
        hash = (29 * hash) + getUnknownFields().hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    public static cn.yscme.scrolling.auto.douyin.SocialMessage parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static cn.yscme.scrolling.auto.douyin.SocialMessage parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static cn.yscme.scrolling.auto.douyin.SocialMessage parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static cn.yscme.scrolling.auto.douyin.SocialMessage parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static cn.yscme.scrolling.auto.douyin.SocialMessage parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static cn.yscme.scrolling.auto.douyin.SocialMessage parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static cn.yscme.scrolling.auto.douyin.SocialMessage parseFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static cn.yscme.scrolling.auto.douyin.SocialMessage parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static cn.yscme.scrolling.auto.douyin.SocialMessage parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input);
    }

    public static cn.yscme.scrolling.auto.douyin.SocialMessage parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static cn.yscme.scrolling.auto.douyin.SocialMessage parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static cn.yscme.scrolling.auto.douyin.SocialMessage parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() {
        return newBuilder();
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(cn.yscme.scrolling.auto.douyin.SocialMessage prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @java.lang.Override
    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
                ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    /**
     * Protobuf type {@code cn.yscme.scrolling.auto.douyin.SocialMessage}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:cn.yscme.scrolling.auto.douyin.SocialMessage)
            cn.yscme.scrolling.auto.douyin.SocialMessageOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return cn.yscme.scrolling.auto.douyin.Douyin.internal_static_cn_yscme_scrolling_auto_douyin_SocialMessage_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return cn.yscme.scrolling.auto.douyin.Douyin.internal_static_cn_yscme_scrolling_auto_douyin_SocialMessage_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            cn.yscme.scrolling.auto.douyin.SocialMessage.class, cn.yscme.scrolling.auto.douyin.SocialMessage.Builder.class);
        }

        // Construct using cn.yscme.scrolling.auto.douyin.SocialMessage.newBuilder()
        private Builder() {
            maybeForceBuilderInitialization();
        }

        private Builder(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
        }

        private void maybeForceBuilderInitialization() {
            if (com.google.protobuf.GeneratedMessageV3
                    .alwaysUseFieldBuilders) {
                getCommonFieldBuilder();
                getUserFieldBuilder();
                getPublicAreaCommonFieldBuilder();
            }
        }

        @java.lang.Override
        public Builder clear() {
            super.clear();
            bitField0_ = 0;
            common_ = null;
            if (commonBuilder_ != null) {
                commonBuilder_.dispose();
                commonBuilder_ = null;
            }
            user_ = null;
            if (userBuilder_ != null) {
                userBuilder_.dispose();
                userBuilder_ = null;
            }
            shareType_ = 0L;
            action_ = 0L;
            shareTarget_ = "";
            followCount_ = 0L;
            publicAreaCommon_ = null;
            if (publicAreaCommonBuilder_ != null) {
                publicAreaCommonBuilder_.dispose();
                publicAreaCommonBuilder_ = null;
            }
            return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
            return cn.yscme.scrolling.auto.douyin.Douyin.internal_static_cn_yscme_scrolling_auto_douyin_SocialMessage_descriptor;
        }

        @java.lang.Override
        public cn.yscme.scrolling.auto.douyin.SocialMessage getDefaultInstanceForType() {
            return cn.yscme.scrolling.auto.douyin.SocialMessage.getDefaultInstance();
        }

        @java.lang.Override
        public cn.yscme.scrolling.auto.douyin.SocialMessage build() {
            cn.yscme.scrolling.auto.douyin.SocialMessage result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        @java.lang.Override
        public cn.yscme.scrolling.auto.douyin.SocialMessage buildPartial() {
            cn.yscme.scrolling.auto.douyin.SocialMessage result = new cn.yscme.scrolling.auto.douyin.SocialMessage(this);
            if (bitField0_ != 0) {
                buildPartial0(result);
            }
            onBuilt();
            return result;
        }

        private void buildPartial0(cn.yscme.scrolling.auto.douyin.SocialMessage result) {
            int from_bitField0_ = bitField0_;
            int to_bitField0_ = 0;
            if (((from_bitField0_ & 0x00000001) != 0)) {
                result.common_ = commonBuilder_ == null
                        ? common_
                        : commonBuilder_.build();
                to_bitField0_ |= 0x00000001;
            }
            if (((from_bitField0_ & 0x00000002) != 0)) {
                result.user_ = userBuilder_ == null
                        ? user_
                        : userBuilder_.build();
                to_bitField0_ |= 0x00000002;
            }
            if (((from_bitField0_ & 0x00000004) != 0)) {
                result.shareType_ = shareType_;
            }
            if (((from_bitField0_ & 0x00000008) != 0)) {
                result.action_ = action_;
            }
            if (((from_bitField0_ & 0x00000010) != 0)) {
                result.shareTarget_ = shareTarget_;
            }
            if (((from_bitField0_ & 0x00000020) != 0)) {
                result.followCount_ = followCount_;
            }
            if (((from_bitField0_ & 0x00000040) != 0)) {
                result.publicAreaCommon_ = publicAreaCommonBuilder_ == null
                        ? publicAreaCommon_
                        : publicAreaCommonBuilder_.build();
                to_bitField0_ |= 0x00000004;
            }
            result.bitField0_ |= to_bitField0_;
        }

        @java.lang.Override
        public Builder clone() {
            return super.clone();
        }

        @java.lang.Override
        public Builder setField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                java.lang.Object value) {
            return super.setField(field, value);
        }

        @java.lang.Override
        public Builder clearField(
                com.google.protobuf.Descriptors.FieldDescriptor field) {
            return super.clearField(field);
        }

        @java.lang.Override
        public Builder clearOneof(
                com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return super.clearOneof(oneof);
        }

        @java.lang.Override
        public Builder setRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                int index, java.lang.Object value) {
            return super.setRepeatedField(field, index, value);
        }

        @java.lang.Override
        public Builder addRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                java.lang.Object value) {
            return super.addRepeatedField(field, value);
        }

        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof cn.yscme.scrolling.auto.douyin.SocialMessage) {
                return mergeFrom((cn.yscme.scrolling.auto.douyin.SocialMessage) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(cn.yscme.scrolling.auto.douyin.SocialMessage other) {
            if (other == cn.yscme.scrolling.auto.douyin.SocialMessage.getDefaultInstance()) return this;
            if (other.hasCommon()) {
                mergeCommon(other.getCommon());
            }
            if (other.hasUser()) {
                mergeUser(other.getUser());
            }
            if (other.getShareType() != 0L) {
                setShareType(other.getShareType());
            }
            if (other.getAction() != 0L) {
                setAction(other.getAction());
            }
            if (!other.getShareTarget().isEmpty()) {
                shareTarget_ = other.shareTarget_;
                bitField0_ |= 0x00000010;
                onChanged();
            }
            if (other.getFollowCount() != 0L) {
                setFollowCount(other.getFollowCount());
            }
            if (other.hasPublicAreaCommon()) {
                mergePublicAreaCommon(other.getPublicAreaCommon());
            }
            this.mergeUnknownFields(other.getUnknownFields());
            onChanged();
            return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
            return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 10: {
                            input.readMessage(
                                    getCommonFieldBuilder().getBuilder(),
                                    extensionRegistry);
                            bitField0_ |= 0x00000001;
                            break;
                        } // case 10
                        case 18: {
                            input.readMessage(
                                    getUserFieldBuilder().getBuilder(),
                                    extensionRegistry);
                            bitField0_ |= 0x00000002;
                            break;
                        } // case 18
                        case 24: {
                            shareType_ = input.readUInt64();
                            bitField0_ |= 0x00000004;
                            break;
                        } // case 24
                        case 32: {
                            action_ = input.readUInt64();
                            bitField0_ |= 0x00000008;
                            break;
                        } // case 32
                        case 42: {
                            shareTarget_ = input.readStringRequireUtf8();
                            bitField0_ |= 0x00000010;
                            break;
                        } // case 42
                        case 48: {
                            followCount_ = input.readUInt64();
                            bitField0_ |= 0x00000020;
                            break;
                        } // case 48
                        case 58: {
                            input.readMessage(
                                    getPublicAreaCommonFieldBuilder().getBuilder(),
                                    extensionRegistry);
                            bitField0_ |= 0x00000040;
                            break;
                        } // case 58
                        default: {
                            if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                                done = true; // was an endgroup tag
                            }
                            break;
                        } // default:
                    } // switch (tag)
                } // while (!done)
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.unwrapIOException();
            } finally {
                onChanged();
            } // finally
            return this;
        }

        private int bitField0_;

        private cn.yscme.scrolling.auto.douyin.Common common_;
        private com.google.protobuf.SingleFieldBuilderV3<
                cn.yscme.scrolling.auto.douyin.Common, cn.yscme.scrolling.auto.douyin.Common.Builder, cn.yscme.scrolling.auto.douyin.CommonOrBuilder> commonBuilder_;

        /**
         * <code>.cn.yscme.scrolling.auto.douyin.Common common = 1;</code>
         *
         * @return Whether the common field is set.
         */
        public boolean hasCommon() {
            return ((bitField0_ & 0x00000001) != 0);
        }

        /**
         * <code>.cn.yscme.scrolling.auto.douyin.Common common = 1;</code>
         *
         * @return The common.
         */
        public cn.yscme.scrolling.auto.douyin.Common getCommon() {
            if (commonBuilder_ == null) {
                return common_ == null ? cn.yscme.scrolling.auto.douyin.Common.getDefaultInstance() : common_;
            } else {
                return commonBuilder_.getMessage();
            }
        }

        /**
         * <code>.cn.yscme.scrolling.auto.douyin.Common common = 1;</code>
         */
        public Builder setCommon(cn.yscme.scrolling.auto.douyin.Common value) {
            if (commonBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                common_ = value;
            } else {
                commonBuilder_.setMessage(value);
            }
            bitField0_ |= 0x00000001;
            onChanged();
            return this;
        }

        /**
         * <code>.cn.yscme.scrolling.auto.douyin.Common common = 1;</code>
         */
        public Builder setCommon(
                cn.yscme.scrolling.auto.douyin.Common.Builder builderForValue) {
            if (commonBuilder_ == null) {
                common_ = builderForValue.build();
            } else {
                commonBuilder_.setMessage(builderForValue.build());
            }
            bitField0_ |= 0x00000001;
            onChanged();
            return this;
        }

        /**
         * <code>.cn.yscme.scrolling.auto.douyin.Common common = 1;</code>
         */
        public Builder mergeCommon(cn.yscme.scrolling.auto.douyin.Common value) {
            if (commonBuilder_ == null) {
                if (((bitField0_ & 0x00000001) != 0) &&
                        common_ != null &&
                        common_ != cn.yscme.scrolling.auto.douyin.Common.getDefaultInstance()) {
                    getCommonBuilder().mergeFrom(value);
                } else {
                    common_ = value;
                }
            } else {
                commonBuilder_.mergeFrom(value);
            }
            if (common_ != null) {
                bitField0_ |= 0x00000001;
                onChanged();
            }
            return this;
        }

        /**
         * <code>.cn.yscme.scrolling.auto.douyin.Common common = 1;</code>
         */
        public Builder clearCommon() {
            bitField0_ = (bitField0_ & ~0x00000001);
            common_ = null;
            if (commonBuilder_ != null) {
                commonBuilder_.dispose();
                commonBuilder_ = null;
            }
            onChanged();
            return this;
        }

        /**
         * <code>.cn.yscme.scrolling.auto.douyin.Common common = 1;</code>
         */
        public cn.yscme.scrolling.auto.douyin.Common.Builder getCommonBuilder() {
            bitField0_ |= 0x00000001;
            onChanged();
            return getCommonFieldBuilder().getBuilder();
        }

        /**
         * <code>.cn.yscme.scrolling.auto.douyin.Common common = 1;</code>
         */
        public cn.yscme.scrolling.auto.douyin.CommonOrBuilder getCommonOrBuilder() {
            if (commonBuilder_ != null) {
                return commonBuilder_.getMessageOrBuilder();
            } else {
                return common_ == null ?
                        cn.yscme.scrolling.auto.douyin.Common.getDefaultInstance() : common_;
            }
        }

        /**
         * <code>.cn.yscme.scrolling.auto.douyin.Common common = 1;</code>
         */
        private com.google.protobuf.SingleFieldBuilderV3<
                cn.yscme.scrolling.auto.douyin.Common, cn.yscme.scrolling.auto.douyin.Common.Builder, cn.yscme.scrolling.auto.douyin.CommonOrBuilder>
        getCommonFieldBuilder() {
            if (commonBuilder_ == null) {
                commonBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                        cn.yscme.scrolling.auto.douyin.Common, cn.yscme.scrolling.auto.douyin.Common.Builder, cn.yscme.scrolling.auto.douyin.CommonOrBuilder>(
                        getCommon(),
                        getParentForChildren(),
                        isClean());
                common_ = null;
            }
            return commonBuilder_;
        }

        private cn.yscme.scrolling.auto.douyin.User user_;
        private com.google.protobuf.SingleFieldBuilderV3<
                cn.yscme.scrolling.auto.douyin.User, cn.yscme.scrolling.auto.douyin.User.Builder, cn.yscme.scrolling.auto.douyin.UserOrBuilder> userBuilder_;

        /**
         * <code>.cn.yscme.scrolling.auto.douyin.User user = 2;</code>
         *
         * @return Whether the user field is set.
         */
        public boolean hasUser() {
            return ((bitField0_ & 0x00000002) != 0);
        }

        /**
         * <code>.cn.yscme.scrolling.auto.douyin.User user = 2;</code>
         *
         * @return The user.
         */
        public cn.yscme.scrolling.auto.douyin.User getUser() {
            if (userBuilder_ == null) {
                return user_ == null ? cn.yscme.scrolling.auto.douyin.User.getDefaultInstance() : user_;
            } else {
                return userBuilder_.getMessage();
            }
        }

        /**
         * <code>.cn.yscme.scrolling.auto.douyin.User user = 2;</code>
         */
        public Builder setUser(cn.yscme.scrolling.auto.douyin.User value) {
            if (userBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                user_ = value;
            } else {
                userBuilder_.setMessage(value);
            }
            bitField0_ |= 0x00000002;
            onChanged();
            return this;
        }

        /**
         * <code>.cn.yscme.scrolling.auto.douyin.User user = 2;</code>
         */
        public Builder setUser(
                cn.yscme.scrolling.auto.douyin.User.Builder builderForValue) {
            if (userBuilder_ == null) {
                user_ = builderForValue.build();
            } else {
                userBuilder_.setMessage(builderForValue.build());
            }
            bitField0_ |= 0x00000002;
            onChanged();
            return this;
        }

        /**
         * <code>.cn.yscme.scrolling.auto.douyin.User user = 2;</code>
         */
        public Builder mergeUser(cn.yscme.scrolling.auto.douyin.User value) {
            if (userBuilder_ == null) {
                if (((bitField0_ & 0x00000002) != 0) &&
                        user_ != null &&
                        user_ != cn.yscme.scrolling.auto.douyin.User.getDefaultInstance()) {
                    getUserBuilder().mergeFrom(value);
                } else {
                    user_ = value;
                }
            } else {
                userBuilder_.mergeFrom(value);
            }
            if (user_ != null) {
                bitField0_ |= 0x00000002;
                onChanged();
            }
            return this;
        }

        /**
         * <code>.cn.yscme.scrolling.auto.douyin.User user = 2;</code>
         */
        public Builder clearUser() {
            bitField0_ = (bitField0_ & ~0x00000002);
            user_ = null;
            if (userBuilder_ != null) {
                userBuilder_.dispose();
                userBuilder_ = null;
            }
            onChanged();
            return this;
        }

        /**
         * <code>.cn.yscme.scrolling.auto.douyin.User user = 2;</code>
         */
        public cn.yscme.scrolling.auto.douyin.User.Builder getUserBuilder() {
            bitField0_ |= 0x00000002;
            onChanged();
            return getUserFieldBuilder().getBuilder();
        }

        /**
         * <code>.cn.yscme.scrolling.auto.douyin.User user = 2;</code>
         */
        public cn.yscme.scrolling.auto.douyin.UserOrBuilder getUserOrBuilder() {
            if (userBuilder_ != null) {
                return userBuilder_.getMessageOrBuilder();
            } else {
                return user_ == null ?
                        cn.yscme.scrolling.auto.douyin.User.getDefaultInstance() : user_;
            }
        }

        /**
         * <code>.cn.yscme.scrolling.auto.douyin.User user = 2;</code>
         */
        private com.google.protobuf.SingleFieldBuilderV3<
                cn.yscme.scrolling.auto.douyin.User, cn.yscme.scrolling.auto.douyin.User.Builder, cn.yscme.scrolling.auto.douyin.UserOrBuilder>
        getUserFieldBuilder() {
            if (userBuilder_ == null) {
                userBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                        cn.yscme.scrolling.auto.douyin.User, cn.yscme.scrolling.auto.douyin.User.Builder, cn.yscme.scrolling.auto.douyin.UserOrBuilder>(
                        getUser(),
                        getParentForChildren(),
                        isClean());
                user_ = null;
            }
            return userBuilder_;
        }

        private long shareType_;

        /**
         * <code>uint64 shareType = 3;</code>
         *
         * @return The shareType.
         */
        @java.lang.Override
        public long getShareType() {
            return shareType_;
        }

        /**
         * <code>uint64 shareType = 3;</code>
         *
         * @param value The shareType to set.
         * @return This builder for chaining.
         */
        public Builder setShareType(long value) {

            shareType_ = value;
            bitField0_ |= 0x00000004;
            onChanged();
            return this;
        }

        /**
         * <code>uint64 shareType = 3;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearShareType() {
            bitField0_ = (bitField0_ & ~0x00000004);
            shareType_ = 0L;
            onChanged();
            return this;
        }

        private long action_;

        /**
         * <code>uint64 action = 4;</code>
         *
         * @return The action.
         */
        @java.lang.Override
        public long getAction() {
            return action_;
        }

        /**
         * <code>uint64 action = 4;</code>
         *
         * @param value The action to set.
         * @return This builder for chaining.
         */
        public Builder setAction(long value) {

            action_ = value;
            bitField0_ |= 0x00000008;
            onChanged();
            return this;
        }

        /**
         * <code>uint64 action = 4;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearAction() {
            bitField0_ = (bitField0_ & ~0x00000008);
            action_ = 0L;
            onChanged();
            return this;
        }

        private java.lang.Object shareTarget_ = "";

        /**
         * <code>string shareTarget = 5;</code>
         *
         * @return The shareTarget.
         */
        public java.lang.String getShareTarget() {
            java.lang.Object ref = shareTarget_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                shareTarget_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <code>string shareTarget = 5;</code>
         *
         * @return The bytes for shareTarget.
         */
        public com.google.protobuf.ByteString
        getShareTargetBytes() {
            java.lang.Object ref = shareTarget_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                shareTarget_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string shareTarget = 5;</code>
         *
         * @param value The shareTarget to set.
         * @return This builder for chaining.
         */
        public Builder setShareTarget(
                java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }
            shareTarget_ = value;
            bitField0_ |= 0x00000010;
            onChanged();
            return this;
        }

        /**
         * <code>string shareTarget = 5;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearShareTarget() {
            shareTarget_ = getDefaultInstance().getShareTarget();
            bitField0_ = (bitField0_ & ~0x00000010);
            onChanged();
            return this;
        }

        /**
         * <code>string shareTarget = 5;</code>
         *
         * @param value The bytes for shareTarget to set.
         * @return This builder for chaining.
         */
        public Builder setShareTargetBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);
            shareTarget_ = value;
            bitField0_ |= 0x00000010;
            onChanged();
            return this;
        }

        private long followCount_;

        /**
         * <code>uint64 followCount = 6;</code>
         *
         * @return The followCount.
         */
        @java.lang.Override
        public long getFollowCount() {
            return followCount_;
        }

        /**
         * <code>uint64 followCount = 6;</code>
         *
         * @param value The followCount to set.
         * @return This builder for chaining.
         */
        public Builder setFollowCount(long value) {

            followCount_ = value;
            bitField0_ |= 0x00000020;
            onChanged();
            return this;
        }

        /**
         * <code>uint64 followCount = 6;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearFollowCount() {
            bitField0_ = (bitField0_ & ~0x00000020);
            followCount_ = 0L;
            onChanged();
            return this;
        }

        private cn.yscme.scrolling.auto.douyin.PublicAreaCommon publicAreaCommon_;
        private com.google.protobuf.SingleFieldBuilderV3<
                cn.yscme.scrolling.auto.douyin.PublicAreaCommon, cn.yscme.scrolling.auto.douyin.PublicAreaCommon.Builder, cn.yscme.scrolling.auto.douyin.PublicAreaCommonOrBuilder> publicAreaCommonBuilder_;

        /**
         * <code>.cn.yscme.scrolling.auto.douyin.PublicAreaCommon publicAreaCommon = 7;</code>
         *
         * @return Whether the publicAreaCommon field is set.
         */
        public boolean hasPublicAreaCommon() {
            return ((bitField0_ & 0x00000040) != 0);
        }

        /**
         * <code>.cn.yscme.scrolling.auto.douyin.PublicAreaCommon publicAreaCommon = 7;</code>
         *
         * @return The publicAreaCommon.
         */
        public cn.yscme.scrolling.auto.douyin.PublicAreaCommon getPublicAreaCommon() {
            if (publicAreaCommonBuilder_ == null) {
                return publicAreaCommon_ == null ? cn.yscme.scrolling.auto.douyin.PublicAreaCommon.getDefaultInstance() : publicAreaCommon_;
            } else {
                return publicAreaCommonBuilder_.getMessage();
            }
        }

        /**
         * <code>.cn.yscme.scrolling.auto.douyin.PublicAreaCommon publicAreaCommon = 7;</code>
         */
        public Builder setPublicAreaCommon(cn.yscme.scrolling.auto.douyin.PublicAreaCommon value) {
            if (publicAreaCommonBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                publicAreaCommon_ = value;
            } else {
                publicAreaCommonBuilder_.setMessage(value);
            }
            bitField0_ |= 0x00000040;
            onChanged();
            return this;
        }

        /**
         * <code>.cn.yscme.scrolling.auto.douyin.PublicAreaCommon publicAreaCommon = 7;</code>
         */
        public Builder setPublicAreaCommon(
                cn.yscme.scrolling.auto.douyin.PublicAreaCommon.Builder builderForValue) {
            if (publicAreaCommonBuilder_ == null) {
                publicAreaCommon_ = builderForValue.build();
            } else {
                publicAreaCommonBuilder_.setMessage(builderForValue.build());
            }
            bitField0_ |= 0x00000040;
            onChanged();
            return this;
        }

        /**
         * <code>.cn.yscme.scrolling.auto.douyin.PublicAreaCommon publicAreaCommon = 7;</code>
         */
        public Builder mergePublicAreaCommon(cn.yscme.scrolling.auto.douyin.PublicAreaCommon value) {
            if (publicAreaCommonBuilder_ == null) {
                if (((bitField0_ & 0x00000040) != 0) &&
                        publicAreaCommon_ != null &&
                        publicAreaCommon_ != cn.yscme.scrolling.auto.douyin.PublicAreaCommon.getDefaultInstance()) {
                    getPublicAreaCommonBuilder().mergeFrom(value);
                } else {
                    publicAreaCommon_ = value;
                }
            } else {
                publicAreaCommonBuilder_.mergeFrom(value);
            }
            if (publicAreaCommon_ != null) {
                bitField0_ |= 0x00000040;
                onChanged();
            }
            return this;
        }

        /**
         * <code>.cn.yscme.scrolling.auto.douyin.PublicAreaCommon publicAreaCommon = 7;</code>
         */
        public Builder clearPublicAreaCommon() {
            bitField0_ = (bitField0_ & ~0x00000040);
            publicAreaCommon_ = null;
            if (publicAreaCommonBuilder_ != null) {
                publicAreaCommonBuilder_.dispose();
                publicAreaCommonBuilder_ = null;
            }
            onChanged();
            return this;
        }

        /**
         * <code>.cn.yscme.scrolling.auto.douyin.PublicAreaCommon publicAreaCommon = 7;</code>
         */
        public cn.yscme.scrolling.auto.douyin.PublicAreaCommon.Builder getPublicAreaCommonBuilder() {
            bitField0_ |= 0x00000040;
            onChanged();
            return getPublicAreaCommonFieldBuilder().getBuilder();
        }

        /**
         * <code>.cn.yscme.scrolling.auto.douyin.PublicAreaCommon publicAreaCommon = 7;</code>
         */
        public cn.yscme.scrolling.auto.douyin.PublicAreaCommonOrBuilder getPublicAreaCommonOrBuilder() {
            if (publicAreaCommonBuilder_ != null) {
                return publicAreaCommonBuilder_.getMessageOrBuilder();
            } else {
                return publicAreaCommon_ == null ?
                        cn.yscme.scrolling.auto.douyin.PublicAreaCommon.getDefaultInstance() : publicAreaCommon_;
            }
        }

        /**
         * <code>.cn.yscme.scrolling.auto.douyin.PublicAreaCommon publicAreaCommon = 7;</code>
         */
        private com.google.protobuf.SingleFieldBuilderV3<
                cn.yscme.scrolling.auto.douyin.PublicAreaCommon, cn.yscme.scrolling.auto.douyin.PublicAreaCommon.Builder, cn.yscme.scrolling.auto.douyin.PublicAreaCommonOrBuilder>
        getPublicAreaCommonFieldBuilder() {
            if (publicAreaCommonBuilder_ == null) {
                publicAreaCommonBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                        cn.yscme.scrolling.auto.douyin.PublicAreaCommon, cn.yscme.scrolling.auto.douyin.PublicAreaCommon.Builder, cn.yscme.scrolling.auto.douyin.PublicAreaCommonOrBuilder>(
                        getPublicAreaCommon(),
                        getParentForChildren(),
                        isClean());
                publicAreaCommon_ = null;
            }
            return publicAreaCommonBuilder_;
        }

        @java.lang.Override
        public final Builder setUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:cn.yscme.scrolling.auto.douyin.SocialMessage)
    }

    // @@protoc_insertion_point(class_scope:cn.yscme.scrolling.auto.douyin.SocialMessage)
    private static final cn.yscme.scrolling.auto.douyin.SocialMessage DEFAULT_INSTANCE;

    static {
        DEFAULT_INSTANCE = new cn.yscme.scrolling.auto.douyin.SocialMessage();
    }

    public static cn.yscme.scrolling.auto.douyin.SocialMessage getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SocialMessage>
            PARSER = new com.google.protobuf.AbstractParser<SocialMessage>() {
        @java.lang.Override
        public SocialMessage parsePartialFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            Builder builder = newBuilder();
            try {
                builder.mergeFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(builder.buildPartial());
            } catch (com.google.protobuf.UninitializedMessageException e) {
                throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(e)
                        .setUnfinishedMessage(builder.buildPartial());
            }
            return builder.buildPartial();
        }
    };

    public static com.google.protobuf.Parser<SocialMessage> parser() {
        return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SocialMessage> getParserForType() {
        return PARSER;
    }

    @java.lang.Override
    public cn.yscme.scrolling.auto.douyin.SocialMessage getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }

}

