// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: douyin.proto

// Protobuf Java Version: 3.25.1
package cn.yscme.scrolling.auto.douyin;

public interface TextOrBuilder extends
        // @@protoc_insertion_point(interface_extends:cn.yscme.scrolling.auto.douyin.Text)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string key = 1;</code>
     *
     * @return The key.
     */
    java.lang.String getKey();

    /**
     * <code>string key = 1;</code>
     *
     * @return The bytes for key.
     */
    com.google.protobuf.ByteString
    getKeyBytes();

    /**
     * <code>string defaultPatter = 2;</code>
     *
     * @return The defaultPatter.
     */
    java.lang.String getDefaultPatter();

    /**
     * <code>string defaultPatter = 2;</code>
     *
     * @return The bytes for defaultPatter.
     */
    com.google.protobuf.ByteString
    getDefaultPatterBytes();

    /**
     * <code>.cn.yscme.scrolling.auto.douyin.TextFormat defaultFormat = 3;</code>
     *
     * @return Whether the defaultFormat field is set.
     */
    boolean hasDefaultFormat();

    /**
     * <code>.cn.yscme.scrolling.auto.douyin.TextFormat defaultFormat = 3;</code>
     *
     * @return The defaultFormat.
     */
    cn.yscme.scrolling.auto.douyin.TextFormat getDefaultFormat();

    /**
     * <code>.cn.yscme.scrolling.auto.douyin.TextFormat defaultFormat = 3;</code>
     */
    cn.yscme.scrolling.auto.douyin.TextFormatOrBuilder getDefaultFormatOrBuilder();

    /**
     * <code>repeated .cn.yscme.scrolling.auto.douyin.TextPiece piecesList = 4;</code>
     */
    java.util.List<cn.yscme.scrolling.auto.douyin.TextPiece>
    getPiecesListList();

    /**
     * <code>repeated .cn.yscme.scrolling.auto.douyin.TextPiece piecesList = 4;</code>
     */
    cn.yscme.scrolling.auto.douyin.TextPiece getPiecesList(int index);

    /**
     * <code>repeated .cn.yscme.scrolling.auto.douyin.TextPiece piecesList = 4;</code>
     */
    int getPiecesListCount();

    /**
     * <code>repeated .cn.yscme.scrolling.auto.douyin.TextPiece piecesList = 4;</code>
     */
    java.util.List<? extends cn.yscme.scrolling.auto.douyin.TextPieceOrBuilder>
    getPiecesListOrBuilderList();

    /**
     * <code>repeated .cn.yscme.scrolling.auto.douyin.TextPiece piecesList = 4;</code>
     */
    cn.yscme.scrolling.auto.douyin.TextPieceOrBuilder getPiecesListOrBuilder(
            int index);
}
