// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: douyin.proto

// Protobuf Java Version: 3.25.1
package cn.yscme.scrolling.auto.douyin;

/**
 * Protobuf type {@code cn.yscme.scrolling.auto.douyin.TextPieceGift}
 */
public final class TextPieceGift extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:cn.yscme.scrolling.auto.douyin.TextPieceGift)
        TextPieceGiftOrBuilder {
    private static final long serialVersionUID = 0L;

    // Use TextPieceGift.newBuilder() to construct.
    private TextPieceGift(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
    }

    private TextPieceGift() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
            UnusedPrivateParameter unused) {
        return new TextPieceGift();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
        return cn.yscme.scrolling.auto.douyin.Douyin.internal_static_cn_yscme_scrolling_auto_douyin_TextPieceGift_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
        return cn.yscme.scrolling.auto.douyin.Douyin.internal_static_cn_yscme_scrolling_auto_douyin_TextPieceGift_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        cn.yscme.scrolling.auto.douyin.TextPieceGift.class, cn.yscme.scrolling.auto.douyin.TextPieceGift.Builder.class);
    }

    private int bitField0_;
    public static final int GIFTID_FIELD_NUMBER = 1;
    private long giftId_ = 0L;

    /**
     * <code>uint64 giftId = 1;</code>
     *
     * @return The giftId.
     */
    @java.lang.Override
    public long getGiftId() {
        return giftId_;
    }

    public static final int NAMEREF_FIELD_NUMBER = 2;
    private cn.yscme.scrolling.auto.douyin.PatternRef nameRef_;

    /**
     * <code>.cn.yscme.scrolling.auto.douyin.PatternRef nameRef = 2;</code>
     *
     * @return Whether the nameRef field is set.
     */
    @java.lang.Override
    public boolean hasNameRef() {
        return ((bitField0_ & 0x00000001) != 0);
    }

    /**
     * <code>.cn.yscme.scrolling.auto.douyin.PatternRef nameRef = 2;</code>
     *
     * @return The nameRef.
     */
    @java.lang.Override
    public cn.yscme.scrolling.auto.douyin.PatternRef getNameRef() {
        return nameRef_ == null ? cn.yscme.scrolling.auto.douyin.PatternRef.getDefaultInstance() : nameRef_;
    }

    /**
     * <code>.cn.yscme.scrolling.auto.douyin.PatternRef nameRef = 2;</code>
     */
    @java.lang.Override
    public cn.yscme.scrolling.auto.douyin.PatternRefOrBuilder getNameRefOrBuilder() {
        return nameRef_ == null ? cn.yscme.scrolling.auto.douyin.PatternRef.getDefaultInstance() : nameRef_;
    }

    private byte memoizedIsInitialized = -1;

    @java.lang.Override
    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
        if (giftId_ != 0L) {
            output.writeUInt64(1, giftId_);
        }
        if (((bitField0_ & 0x00000001) != 0)) {
            output.writeMessage(2, getNameRef());
        }
        getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (giftId_ != 0L) {
            size += com.google.protobuf.CodedOutputStream
                    .computeUInt64Size(1, giftId_);
        }
        if (((bitField0_ & 0x00000001) != 0)) {
            size += com.google.protobuf.CodedOutputStream
                    .computeMessageSize(2, getNameRef());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof cn.yscme.scrolling.auto.douyin.TextPieceGift)) {
            return super.equals(obj);
        }
        cn.yscme.scrolling.auto.douyin.TextPieceGift other = (cn.yscme.scrolling.auto.douyin.TextPieceGift) obj;

        if (getGiftId()
                != other.getGiftId()) return false;
        if (hasNameRef() != other.hasNameRef()) return false;
        if (hasNameRef()) {
            if (!getNameRef()
                    .equals(other.getNameRef())) return false;
        }
        if (!getUnknownFields().equals(other.getUnknownFields())) return false;
        return true;
    }

    @java.lang.Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + GIFTID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                getGiftId());
        if (hasNameRef()) {
            hash = (37 * hash) + NAMEREF_FIELD_NUMBER;
            hash = (53 * hash) + getNameRef().hashCode();
        }
        hash = (29 * hash) + getUnknownFields().hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    public static cn.yscme.scrolling.auto.douyin.TextPieceGift parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static cn.yscme.scrolling.auto.douyin.TextPieceGift parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static cn.yscme.scrolling.auto.douyin.TextPieceGift parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static cn.yscme.scrolling.auto.douyin.TextPieceGift parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static cn.yscme.scrolling.auto.douyin.TextPieceGift parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static cn.yscme.scrolling.auto.douyin.TextPieceGift parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static cn.yscme.scrolling.auto.douyin.TextPieceGift parseFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static cn.yscme.scrolling.auto.douyin.TextPieceGift parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static cn.yscme.scrolling.auto.douyin.TextPieceGift parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input);
    }

    public static cn.yscme.scrolling.auto.douyin.TextPieceGift parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static cn.yscme.scrolling.auto.douyin.TextPieceGift parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static cn.yscme.scrolling.auto.douyin.TextPieceGift parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() {
        return newBuilder();
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(cn.yscme.scrolling.auto.douyin.TextPieceGift prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @java.lang.Override
    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
                ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    /**
     * Protobuf type {@code cn.yscme.scrolling.auto.douyin.TextPieceGift}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:cn.yscme.scrolling.auto.douyin.TextPieceGift)
            cn.yscme.scrolling.auto.douyin.TextPieceGiftOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return cn.yscme.scrolling.auto.douyin.Douyin.internal_static_cn_yscme_scrolling_auto_douyin_TextPieceGift_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return cn.yscme.scrolling.auto.douyin.Douyin.internal_static_cn_yscme_scrolling_auto_douyin_TextPieceGift_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            cn.yscme.scrolling.auto.douyin.TextPieceGift.class, cn.yscme.scrolling.auto.douyin.TextPieceGift.Builder.class);
        }

        // Construct using cn.yscme.scrolling.auto.douyin.TextPieceGift.newBuilder()
        private Builder() {
            maybeForceBuilderInitialization();
        }

        private Builder(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
        }

        private void maybeForceBuilderInitialization() {
            if (com.google.protobuf.GeneratedMessageV3
                    .alwaysUseFieldBuilders) {
                getNameRefFieldBuilder();
            }
        }

        @java.lang.Override
        public Builder clear() {
            super.clear();
            bitField0_ = 0;
            giftId_ = 0L;
            nameRef_ = null;
            if (nameRefBuilder_ != null) {
                nameRefBuilder_.dispose();
                nameRefBuilder_ = null;
            }
            return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
            return cn.yscme.scrolling.auto.douyin.Douyin.internal_static_cn_yscme_scrolling_auto_douyin_TextPieceGift_descriptor;
        }

        @java.lang.Override
        public cn.yscme.scrolling.auto.douyin.TextPieceGift getDefaultInstanceForType() {
            return cn.yscme.scrolling.auto.douyin.TextPieceGift.getDefaultInstance();
        }

        @java.lang.Override
        public cn.yscme.scrolling.auto.douyin.TextPieceGift build() {
            cn.yscme.scrolling.auto.douyin.TextPieceGift result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        @java.lang.Override
        public cn.yscme.scrolling.auto.douyin.TextPieceGift buildPartial() {
            cn.yscme.scrolling.auto.douyin.TextPieceGift result = new cn.yscme.scrolling.auto.douyin.TextPieceGift(this);
            if (bitField0_ != 0) {
                buildPartial0(result);
            }
            onBuilt();
            return result;
        }

        private void buildPartial0(cn.yscme.scrolling.auto.douyin.TextPieceGift result) {
            int from_bitField0_ = bitField0_;
            if (((from_bitField0_ & 0x00000001) != 0)) {
                result.giftId_ = giftId_;
            }
            int to_bitField0_ = 0;
            if (((from_bitField0_ & 0x00000002) != 0)) {
                result.nameRef_ = nameRefBuilder_ == null
                        ? nameRef_
                        : nameRefBuilder_.build();
                to_bitField0_ |= 0x00000001;
            }
            result.bitField0_ |= to_bitField0_;
        }

        @java.lang.Override
        public Builder clone() {
            return super.clone();
        }

        @java.lang.Override
        public Builder setField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                java.lang.Object value) {
            return super.setField(field, value);
        }

        @java.lang.Override
        public Builder clearField(
                com.google.protobuf.Descriptors.FieldDescriptor field) {
            return super.clearField(field);
        }

        @java.lang.Override
        public Builder clearOneof(
                com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return super.clearOneof(oneof);
        }

        @java.lang.Override
        public Builder setRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                int index, java.lang.Object value) {
            return super.setRepeatedField(field, index, value);
        }

        @java.lang.Override
        public Builder addRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                java.lang.Object value) {
            return super.addRepeatedField(field, value);
        }

        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof cn.yscme.scrolling.auto.douyin.TextPieceGift) {
                return mergeFrom((cn.yscme.scrolling.auto.douyin.TextPieceGift) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(cn.yscme.scrolling.auto.douyin.TextPieceGift other) {
            if (other == cn.yscme.scrolling.auto.douyin.TextPieceGift.getDefaultInstance()) return this;
            if (other.getGiftId() != 0L) {
                setGiftId(other.getGiftId());
            }
            if (other.hasNameRef()) {
                mergeNameRef(other.getNameRef());
            }
            this.mergeUnknownFields(other.getUnknownFields());
            onChanged();
            return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
            return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 8: {
                            giftId_ = input.readUInt64();
                            bitField0_ |= 0x00000001;
                            break;
                        } // case 8
                        case 18: {
                            input.readMessage(
                                    getNameRefFieldBuilder().getBuilder(),
                                    extensionRegistry);
                            bitField0_ |= 0x00000002;
                            break;
                        } // case 18
                        default: {
                            if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                                done = true; // was an endgroup tag
                            }
                            break;
                        } // default:
                    } // switch (tag)
                } // while (!done)
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.unwrapIOException();
            } finally {
                onChanged();
            } // finally
            return this;
        }

        private int bitField0_;

        private long giftId_;

        /**
         * <code>uint64 giftId = 1;</code>
         *
         * @return The giftId.
         */
        @java.lang.Override
        public long getGiftId() {
            return giftId_;
        }

        /**
         * <code>uint64 giftId = 1;</code>
         *
         * @param value The giftId to set.
         * @return This builder for chaining.
         */
        public Builder setGiftId(long value) {

            giftId_ = value;
            bitField0_ |= 0x00000001;
            onChanged();
            return this;
        }

        /**
         * <code>uint64 giftId = 1;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearGiftId() {
            bitField0_ = (bitField0_ & ~0x00000001);
            giftId_ = 0L;
            onChanged();
            return this;
        }

        private cn.yscme.scrolling.auto.douyin.PatternRef nameRef_;
        private com.google.protobuf.SingleFieldBuilderV3<
                cn.yscme.scrolling.auto.douyin.PatternRef, cn.yscme.scrolling.auto.douyin.PatternRef.Builder, cn.yscme.scrolling.auto.douyin.PatternRefOrBuilder> nameRefBuilder_;

        /**
         * <code>.cn.yscme.scrolling.auto.douyin.PatternRef nameRef = 2;</code>
         *
         * @return Whether the nameRef field is set.
         */
        public boolean hasNameRef() {
            return ((bitField0_ & 0x00000002) != 0);
        }

        /**
         * <code>.cn.yscme.scrolling.auto.douyin.PatternRef nameRef = 2;</code>
         *
         * @return The nameRef.
         */
        public cn.yscme.scrolling.auto.douyin.PatternRef getNameRef() {
            if (nameRefBuilder_ == null) {
                return nameRef_ == null ? cn.yscme.scrolling.auto.douyin.PatternRef.getDefaultInstance() : nameRef_;
            } else {
                return nameRefBuilder_.getMessage();
            }
        }

        /**
         * <code>.cn.yscme.scrolling.auto.douyin.PatternRef nameRef = 2;</code>
         */
        public Builder setNameRef(cn.yscme.scrolling.auto.douyin.PatternRef value) {
            if (nameRefBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                nameRef_ = value;
            } else {
                nameRefBuilder_.setMessage(value);
            }
            bitField0_ |= 0x00000002;
            onChanged();
            return this;
        }

        /**
         * <code>.cn.yscme.scrolling.auto.douyin.PatternRef nameRef = 2;</code>
         */
        public Builder setNameRef(
                cn.yscme.scrolling.auto.douyin.PatternRef.Builder builderForValue) {
            if (nameRefBuilder_ == null) {
                nameRef_ = builderForValue.build();
            } else {
                nameRefBuilder_.setMessage(builderForValue.build());
            }
            bitField0_ |= 0x00000002;
            onChanged();
            return this;
        }

        /**
         * <code>.cn.yscme.scrolling.auto.douyin.PatternRef nameRef = 2;</code>
         */
        public Builder mergeNameRef(cn.yscme.scrolling.auto.douyin.PatternRef value) {
            if (nameRefBuilder_ == null) {
                if (((bitField0_ & 0x00000002) != 0) &&
                        nameRef_ != null &&
                        nameRef_ != cn.yscme.scrolling.auto.douyin.PatternRef.getDefaultInstance()) {
                    getNameRefBuilder().mergeFrom(value);
                } else {
                    nameRef_ = value;
                }
            } else {
                nameRefBuilder_.mergeFrom(value);
            }
            if (nameRef_ != null) {
                bitField0_ |= 0x00000002;
                onChanged();
            }
            return this;
        }

        /**
         * <code>.cn.yscme.scrolling.auto.douyin.PatternRef nameRef = 2;</code>
         */
        public Builder clearNameRef() {
            bitField0_ = (bitField0_ & ~0x00000002);
            nameRef_ = null;
            if (nameRefBuilder_ != null) {
                nameRefBuilder_.dispose();
                nameRefBuilder_ = null;
            }
            onChanged();
            return this;
        }

        /**
         * <code>.cn.yscme.scrolling.auto.douyin.PatternRef nameRef = 2;</code>
         */
        public cn.yscme.scrolling.auto.douyin.PatternRef.Builder getNameRefBuilder() {
            bitField0_ |= 0x00000002;
            onChanged();
            return getNameRefFieldBuilder().getBuilder();
        }

        /**
         * <code>.cn.yscme.scrolling.auto.douyin.PatternRef nameRef = 2;</code>
         */
        public cn.yscme.scrolling.auto.douyin.PatternRefOrBuilder getNameRefOrBuilder() {
            if (nameRefBuilder_ != null) {
                return nameRefBuilder_.getMessageOrBuilder();
            } else {
                return nameRef_ == null ?
                        cn.yscme.scrolling.auto.douyin.PatternRef.getDefaultInstance() : nameRef_;
            }
        }

        /**
         * <code>.cn.yscme.scrolling.auto.douyin.PatternRef nameRef = 2;</code>
         */
        private com.google.protobuf.SingleFieldBuilderV3<
                cn.yscme.scrolling.auto.douyin.PatternRef, cn.yscme.scrolling.auto.douyin.PatternRef.Builder, cn.yscme.scrolling.auto.douyin.PatternRefOrBuilder>
        getNameRefFieldBuilder() {
            if (nameRefBuilder_ == null) {
                nameRefBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                        cn.yscme.scrolling.auto.douyin.PatternRef, cn.yscme.scrolling.auto.douyin.PatternRef.Builder, cn.yscme.scrolling.auto.douyin.PatternRefOrBuilder>(
                        getNameRef(),
                        getParentForChildren(),
                        isClean());
                nameRef_ = null;
            }
            return nameRefBuilder_;
        }

        @java.lang.Override
        public final Builder setUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:cn.yscme.scrolling.auto.douyin.TextPieceGift)
    }

    // @@protoc_insertion_point(class_scope:cn.yscme.scrolling.auto.douyin.TextPieceGift)
    private static final cn.yscme.scrolling.auto.douyin.TextPieceGift DEFAULT_INSTANCE;

    static {
        DEFAULT_INSTANCE = new cn.yscme.scrolling.auto.douyin.TextPieceGift();
    }

    public static cn.yscme.scrolling.auto.douyin.TextPieceGift getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TextPieceGift>
            PARSER = new com.google.protobuf.AbstractParser<TextPieceGift>() {
        @java.lang.Override
        public TextPieceGift parsePartialFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            Builder builder = newBuilder();
            try {
                builder.mergeFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(builder.buildPartial());
            } catch (com.google.protobuf.UninitializedMessageException e) {
                throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(e)
                        .setUnfinishedMessage(builder.buildPartial());
            }
            return builder.buildPartial();
        }
    };

    public static com.google.protobuf.Parser<TextPieceGift> parser() {
        return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TextPieceGift> getParserForType() {
        return PARSER;
    }

    @java.lang.Override
    public cn.yscme.scrolling.auto.douyin.TextPieceGift getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }

}

