// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: douyin.proto

// Protobuf Java Version: 3.25.1
package cn.yscme.scrolling.auto.douyin;

public interface UserBadgeOrBuilder extends
        // @@protoc_insertion_point(interface_extends:cn.yscme.scrolling.auto.douyin.UserBadge)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>map&lt;int32, .cn.yscme.scrolling.auto.douyin.Image&gt; icons = 1;</code>
     */
    int getIconsCount();

    /**
     * <code>map&lt;int32, .cn.yscme.scrolling.auto.douyin.Image&gt; icons = 1;</code>
     */
    boolean containsIcons(
            int key);

    /**
     * Use {@link #getIconsMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.Integer, cn.yscme.scrolling.auto.douyin.Image>
    getIcons();

    /**
     * <code>map&lt;int32, .cn.yscme.scrolling.auto.douyin.Image&gt; icons = 1;</code>
     */
    java.util.Map<java.lang.Integer, cn.yscme.scrolling.auto.douyin.Image>
    getIconsMap();

    /**
     * <code>map&lt;int32, .cn.yscme.scrolling.auto.douyin.Image&gt; icons = 1;</code>
     */
    /* nullable */
    cn.yscme.scrolling.auto.douyin.Image getIconsOrDefault(
            int key,
            /* nullable */
            cn.yscme.scrolling.auto.douyin.Image defaultValue);

    /**
     * <code>map&lt;int32, .cn.yscme.scrolling.auto.douyin.Image&gt; icons = 1;</code>
     */
    cn.yscme.scrolling.auto.douyin.Image getIconsOrThrow(
            int key);

    /**
     * <code>string title = 2;</code>
     *
     * @return The title.
     */
    java.lang.String getTitle();

    /**
     * <code>string title = 2;</code>
     *
     * @return The bytes for title.
     */
    com.google.protobuf.ByteString
    getTitleBytes();
}
